<?php

namespace App\Support\Compliance;

class ComplianceFrameworkPackCatalog
{
    public static function make(): array
    {
$packVersion = '2026.05.08.2';
$aiActPackVersion = '2026.05.13.1';
$sourceCheckedAt = '2026-05-13';

$sourceRegisters = [
    'ai_act_eu' => [
        'status' => 'verified',
        'scope' => 'eu_baseline',
        'jurisdiction' => 'EU',
        'last_checked_at' => $sourceCheckedAt,
        'sources' => [
            'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
            'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai',
            'https://digital-strategy.ec.europa.eu/en/policies/contents-code-gpai',
            'https://digital-strategy.ec.europa.eu/en/factpages/general-purpose-ai-obligations-under-ai-act',
        ],
    ],
    'nis2_it' => [
        'status' => 'verified',
        'scope' => 'national_overlay',
        'jurisdiction' => 'IT/EU',
        'last_checked_at' => $sourceCheckedAt,
        'sources' => [
            'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
            'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2024-09-04;138!vig=',
            'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
        ],
    ],
    'nis2_eu' => [
        'status' => 'verified',
        'scope' => 'eu_baseline',
        'jurisdiction' => 'EU',
        'last_checked_at' => $sourceCheckedAt,
        'sources' => [
            'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
            'https://digital-strategy.ec.europa.eu/en/policies/nis-transposition',
            'https://www.enisa.europa.eu/topics/state-of-cybersecurity-in-the-eu/cybersecurity-policies/nis-directive-2',
        ],
    ],
    'gdpr_eu' => [
        'status' => 'verified',
        'scope' => 'eu_baseline',
        'jurisdiction' => 'EU',
        'last_checked_at' => $sourceCheckedAt,
        'sources' => [
            'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
        ],
    ],
];

$aiActEnRequirements = [
    [
        'code' => 'AI-GOV-01',
        'title' => 'AI governance, roles and accountability',
        'domain' => 'Governance',
        'obligation_type' => 'ai_governance',
        'evidence_type' => 'register',
        'delegation_level' => 'owner_review',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 - governance and operator responsibilities',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Define AI accountability, operator roles, approval responsibilities and ownership for AI Act evidence.',
        'evidence_guidance' => 'AI governance register, responsible owners, approval minutes, role matrix and review calendar.',
    ],
    [
        'code' => 'AI-INV-01',
        'title' => 'AI system inventory',
        'parent_requirement_code' => 'AI-GOV-01',
        'domain' => 'Inventory',
        'obligation_type' => 'ai_inventory',
        'evidence_type' => 'register',
        'delegation_level' => 'delegable',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 - scope and operator obligations',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 6,
        'description' => 'Maintain an inventory of AI systems, AI-enabled services, intended purpose, users, suppliers and lifecycle status.',
        'evidence_guidance' => 'AI system register with owner, supplier, intended purpose, deployment context, users, data categories and review status.',
    ],
    [
        'code' => 'AI-SCOPE-01',
        'title' => 'AI Act applicability and operator role assessment',
        'parent_requirement_codes' => ['AI-GOV-01', 'AI-INV-01'],
        'domain' => 'Applicability',
        'obligation_type' => 'ai_classification',
        'evidence_type' => 'assessment',
        'delegation_level' => 'consultant_only',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 - definitions and scope',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Assess whether each use case is an AI system and identify the operator role: provider, deployer, importer, distributor or other actor.',
        'evidence_guidance' => 'Applicability assessment, operator role decision, rationale, exclusions and approval by the accountable owner.',
    ],
    [
        'code' => 'AI-PROH-01',
        'title' => 'Prohibited practices assessment',
        'parent_requirement_code' => 'AI-SCOPE-01',
        'domain' => 'Prohibited practices',
        'obligation_type' => 'ai_classification',
        'evidence_type' => 'assessment',
        'delegation_level' => 'consultant_only',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 art. 5',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Document that AI use cases are screened against prohibited AI practices before deployment or material change.',
        'evidence_guidance' => 'Prohibited-practice checklist, legal/owner review, decision log and remediation or stop decision where needed.',
    ],
    [
        'code' => 'AI-LIT-01',
        'title' => 'AI literacy and responsible use',
        'parent_requirement_code' => 'AI-GOV-01',
        'domain' => 'Training',
        'obligation_type' => 'training',
        'evidence_type' => 'training_record',
        'delegation_level' => 'owner_review',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 art. 4',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Track proportionate AI literacy measures for people operating, using or overseeing AI systems.',
        'evidence_guidance' => 'Training plan, attendance, role-based guidance, acceptable-use rules and periodic refresh evidence.',
    ],
    [
        'code' => 'AI-RISK-01',
        'title' => 'Risk classification and high-risk screening',
        'parent_requirement_code' => 'AI-SCOPE-01',
        'domain' => 'Risk classification',
        'obligation_type' => 'ai_classification',
        'evidence_type' => 'assessment',
        'delegation_level' => 'consultant_only',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 arts. 6 and annexes',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Classify each AI system against AI Act risk categories and identify high-risk obligations where applicable.',
        'evidence_guidance' => 'Risk classification worksheet, applicable annex mapping, rationale, approval and next review date.',
    ],
    [
        'code' => 'AI-HR-01',
        'title' => 'High-risk AI risk-management system',
        'parent_requirement_code' => 'AI-RISK-01',
        'domain' => 'High-risk AI',
        'obligation_type' => 'ai_high_risk',
        'evidence_type' => 'assessment',
        'delegation_level' => 'consultant_only',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 art. 9',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Maintain a documented risk-management process for high-risk AI systems where applicable.',
        'evidence_guidance' => 'Risk-management file, hazards, mitigations, residual risk acceptance, test evidence and owner approval.',
    ],
    [
        'code' => 'AI-HR-02',
        'title' => 'Data governance and dataset controls',
        'parent_requirement_code' => 'AI-HR-01',
        'domain' => 'High-risk AI',
        'obligation_type' => 'ai_high_risk',
        'evidence_type' => 'technical_report',
        'delegation_level' => 'owner_review',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 art. 10',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Document data governance, data quality, representativeness, bias controls and lawful data handling for high-risk AI where applicable.',
        'evidence_guidance' => 'Dataset inventory, data quality checks, bias assessment, data lineage, privacy checks and remediation evidence.',
    ],
    [
        'code' => 'AI-HR-03',
        'title' => 'Technical documentation and instructions for use',
        'parent_requirement_code' => 'AI-HR-01',
        'domain' => 'High-risk AI',
        'obligation_type' => 'ai_high_risk',
        'evidence_type' => 'technical_report',
        'delegation_level' => 'owner_review',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 arts. 11 and 13, Annex IV',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Maintain technical documentation and user instructions for high-risk AI systems where applicable.',
        'evidence_guidance' => 'Technical file, intended purpose, limitations, performance, instructions for use and versioned approvals.',
    ],
    [
        'code' => 'AI-HR-04',
        'title' => 'Logging and record keeping',
        'parent_requirement_code' => 'AI-HR-01',
        'domain' => 'High-risk AI',
        'obligation_type' => 'ai_high_risk',
        'evidence_type' => 'technical_report',
        'delegation_level' => 'delegable',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 art. 12',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Define logging and record-retention controls for high-risk AI systems where applicable.',
        'evidence_guidance' => 'Logging design, retention policy, access controls, sample logs, monitoring evidence and review records.',
    ],
    [
        'code' => 'AI-HR-05',
        'title' => 'Transparency and human oversight',
        'parent_requirement_code' => 'AI-HR-01',
        'domain' => 'High-risk AI',
        'obligation_type' => 'ai_high_risk',
        'evidence_type' => 'procedure',
        'delegation_level' => 'owner_review',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 arts. 13 and 14',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Define transparency information and human oversight measures for high-risk AI systems where applicable.',
        'evidence_guidance' => 'User information, oversight procedure, escalation criteria, operator training and decision records.',
    ],
    [
        'code' => 'AI-HR-06',
        'title' => 'Accuracy, robustness and cybersecurity',
        'parent_requirement_code' => 'AI-HR-01',
        'domain' => 'High-risk AI',
        'obligation_type' => 'ai_high_risk',
        'evidence_type' => 'technical_report',
        'delegation_level' => 'owner_review',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 art. 15',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Document accuracy, robustness, resilience and cybersecurity controls for high-risk AI systems where applicable.',
        'evidence_guidance' => 'Performance tests, robustness testing, cybersecurity assessment, monitoring results and corrective actions.',
    ],
    [
        'code' => 'AI-PMM-01',
        'title' => 'Post-market monitoring and serious incident workflow',
        'parent_requirement_codes' => ['AI-RISK-01', 'AI-HR-01'],
        'domain' => 'Monitoring',
        'obligation_type' => 'ai_monitoring',
        'evidence_type' => 'incident_record',
        'delegation_level' => 'consultant_only',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 - post-market monitoring and incident obligations',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Define post-market monitoring, issue handling, serious incident evaluation and reporting workflow where applicable.',
        'evidence_guidance' => 'Monitoring plan, incident register, assessment decisions, authority communications and corrective actions.',
    ],
    [
        'code' => 'AI-GPAI-01',
        'title' => 'GPAI provider obligations',
        'parent_requirement_code' => 'AI-SCOPE-01',
        'domain' => 'GPAI',
        'obligation_type' => 'ai_gpai',
        'evidence_type' => 'technical_report',
        'delegation_level' => 'consultant_only',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 Chapter V and AI Office GPAI guidance',
        'source_url' => 'https://digital-strategy.ec.europa.eu/en/factpages/general-purpose-ai-obligations-under-ai-act',
        'review_frequency_months' => 12,
        'description' => 'Assess whether the organisation is a GPAI model provider and document transparency, copyright and public-summary obligations where applicable.',
        'evidence_guidance' => 'GPAI applicability decision, technical documentation, copyright policy, training-content summary and code-of-practice decision.',
    ],
    [
        'code' => 'AI-GPAI-02',
        'title' => 'GPAI systemic-risk obligations',
        'parent_requirement_code' => 'AI-GPAI-01',
        'domain' => 'GPAI',
        'obligation_type' => 'ai_gpai',
        'evidence_type' => 'assessment',
        'delegation_level' => 'consultant_only',
        'risk_level' => 'not_applicable',
        'official_reference' => 'Regulation (EU) 2024/1689 art. 55 and GPAI Code of Practice Safety and Security chapter',
        'source_url' => 'https://digital-strategy.ec.europa.eu/en/policies/contents-code-gpai',
        'review_frequency_months' => 12,
        'description' => 'Assess systemic-risk GPAI obligations where applicable, including notification, risk assessment, incident reporting and cybersecurity protections.',
        'evidence_guidance' => 'Systemic-risk decision, Commission notification evidence, risk assessment, safety/security measures and incident workflow.',
    ],
    [
        'code' => 'AI-EVD-01',
        'title' => 'Evidence integrity, versioning and checksum trail',
        'parent_requirement_code' => 'AI-GOV-01',
        'domain' => 'Evidence',
        'obligation_type' => 'ai_governance',
        'evidence_type' => 'attestation',
        'delegation_level' => 'owner_review',
        'risk_level' => 'not_applicable',
        'official_reference' => 'AI Act accountability and evidence verifiability',
        'source_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'review_frequency_months' => 12,
        'description' => 'Ensure AI Act evidence has versioning, approval, integrity hashes and signed records where appropriate.',
        'evidence_guidance' => 'Evidence register with SHA-256 checksums, event hash chain, signed versions and review logs.',
    ],
];

$aiActItRequirements = $aiActEnRequirements;
foreach ($aiActItRequirements as &$requirement) {
    $translations = [
        'AI-GOV-01' => ['Governo AI, ruoli e accountability', 'Definire responsabilita AI, ruoli degli operatori, approvazioni e proprieta delle evidenze AI Act.', 'Registro governance AI, responsabili, verbali, matrice ruoli e calendario riesami.'],
        'AI-INV-01' => ['Inventario dei sistemi AI', 'Mantenere un inventario di sistemi AI, servizi abilitati da AI, finalita, utenti, fornitori e stato del ciclo di vita.', 'Registro sistemi AI con owner, fornitore, finalita, contesto di uso, utenti, categorie dati e stato riesame.'],
        'AI-SCOPE-01' => ['Applicabilita AI Act e ruolo operatore', 'Valutare se ogni caso d uso e un sistema AI e identificare il ruolo: provider, deployer, importer, distributor o altro attore.', 'Assessment applicabilita, decisione ruolo operatore, razionale, esclusioni e approvazione owner.'],
        'AI-PROH-01' => ['Verifica pratiche vietate', 'Documentare lo screening dei casi d uso rispetto alle pratiche AI vietate prima della messa in uso o modifica rilevante.', 'Checklist pratiche vietate, revisione legale/owner, registro decisioni e stop/remediation dove necessario.'],
        'AI-LIT-01' => ['AI literacy e uso responsabile', 'Tracciare misure proporzionate di alfabetizzazione AI per chi opera, usa o supervisiona sistemi AI.', 'Piano formazione, presenze, linee guida per ruolo, regole uso accettabile e refresh periodici.'],
        'AI-RISK-01' => ['Classificazione rischio e screening high-risk', 'Classificare ogni sistema AI rispetto alle categorie AI Act e identificare obblighi high-risk ove applicabili.', 'Scheda classificazione rischio, mapping allegati, razionale, approvazione e prossima revisione.'],
        'AI-HR-01' => ['Sistema di gestione rischio per AI high-risk', 'Mantenere un processo documentato di gestione del rischio per sistemi AI high-risk ove applicabile.', 'Risk file, pericoli, mitigazioni, accettazione rischio residuo, test e approvazione owner.'],
        'AI-HR-02' => ['Data governance e controlli dataset', 'Documentare data governance, qualita dati, rappresentativita, controlli bias e trattamento lecito per AI high-risk ove applicabile.', 'Inventario dataset, controlli qualita, bias assessment, lineage dati, controlli privacy e remediation.'],
        'AI-HR-03' => ['Documentazione tecnica e istruzioni d uso', 'Mantenere documentazione tecnica e istruzioni d uso per sistemi AI high-risk ove applicabile.', 'Fascicolo tecnico, finalita prevista, limiti, performance, istruzioni d uso e approvazioni versionate.'],
        'AI-HR-04' => ['Log e conservazione registrazioni', 'Definire controlli di logging e conservazione per sistemi AI high-risk ove applicabile.', 'Disegno logging, policy retention, controlli accesso, log campione, monitoraggio e riesami.'],
        'AI-HR-05' => ['Trasparenza e supervisione umana', 'Definire informazioni di trasparenza e misure di supervisione umana per AI high-risk ove applicabile.', 'Informative utente, procedura oversight, criteri escalation, formazione operatori e decisioni tracciate.'],
        'AI-HR-06' => ['Accuratezza, robustezza e cybersecurity', 'Documentare accuratezza, robustezza, resilienza e controlli cybersecurity per AI high-risk ove applicabile.', 'Test performance, robustness testing, assessment cybersecurity, monitoraggio e azioni correttive.'],
        'AI-PMM-01' => ['Monitoraggio post-market e workflow incidenti gravi', 'Definire monitoraggio post-market, gestione problemi, valutazione incidenti gravi e reporting ove applicabile.', 'Piano monitoraggio, registro incidenti, decisioni assessment, comunicazioni autorita e azioni correttive.'],
        'AI-GPAI-01' => ['Obblighi provider GPAI', 'Valutare se l organizzazione e provider di modelli GPAI e documentare trasparenza, copyright e public summary ove applicabile.', 'Decisione applicabilita GPAI, documentazione tecnica, policy copyright, sintesi contenuti training e decisione sul Code of Practice.'],
        'AI-GPAI-02' => ['Obblighi GPAI con rischio sistemico', 'Valutare obblighi GPAI systemic-risk ove applicabili: notifica, risk assessment, incident reporting e cybersecurity.', 'Decisione systemic-risk, evidenza notifica Commissione, risk assessment, misure safety/security e workflow incidenti.'],
        'AI-EVD-01' => ['Integrita evidenze, versioning e checksum', 'Garantire evidenze AI Act con versioning, approvazione, hash di integrita e firme dove appropriate.', 'Registro evidenze con checksum SHA-256, catena hash eventi, versioni firmate e log di riesame.'],
    ];

    if (isset($translations[$requirement['code']])) {
        [$requirement['title'], $requirement['description'], $requirement['evidence_guidance']] = $translations[$requirement['code']];
    }
}
unset($requirement);
$packs = [
        'nis2_it' => [
            'pack_version' => $packVersion,
            'locale' => 'it-IT',
            'framework' => [
                'name' => 'NIS2 Italia - Matrice di autovalutazione',
                'slug' => 'nis2-it-self-assessment',
                'description' => 'Matrice iniziale per governare documenti, evidenze, deleghe e riesami NIS2.',
                'compliance_objective' => 'Strutturare l\'autovalutazione NIS2 in requisiti tracciabili, evidenze documentali, responsabilita e scadenze di revisione.',
                'authority_name' => 'ACN',
                'framework_code' => 'NIS2-IT',
                'framework_type' => 'law',
                'compliance_domain' => 'nis2',
                'jurisdiction' => 'IT/EU',
                'version' => '2026',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                'sort_order' => 10,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'NIS2-GOV-01',
                    'title' => 'Perimetro, ruoli e responsabilita NIS',
                    'domain' => 'Governance',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'D.Lgs. 138/2024 e Direttiva NIS2 art. 20',
                    'source_url' => 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2024-09-04;138!vig=',
                    'review_frequency_months' => 12,
                    'description' => 'Definire perimetro NIS, responsabili, deleghe operative, punti di contatto e responsabilita di approvazione.',
                    'evidence_guidance' => 'Registro perimetro NIS, organigramma responsabilita, deleghe, punti di contatto e verbale di approvazione.',
                    'applicability_notes' => 'Requisito di governo: non contiene punteggio di rischio, ma deve avere evidenza primaria approvata.',
                ],
                [
                    'code' => 'NIS2-REG-01',
                    'title' => 'Aggiornamento informazioni soggetto NIS',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Registrazione',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'ACN FAQ NIS - Aggiornamento delle informazioni',
                    'source_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                    'review_frequency_months' => 6,
                    'description' => 'Presidiare aggiornamento e coerenza delle informazioni registrate per il soggetto NIS.',
                    'evidence_guidance' => 'Registro informazioni soggetto, responsabili, sedi, servizi rilevanti e data ultima verifica.',
                    'applicability_notes' => 'Da rivedere quando cambiano dati societari, perimetro, referenti o servizi rilevanti.',
                ],
                [
                    'code' => 'NIS2-GOV-02',
                    'title' => 'Approvazione direzione, formazione e consapevolezza',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Governance',
                    'obligation_type' => 'training',
                    'evidence_type' => 'training_record',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 20',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Tracciare approvazione delle misure, responsabilita degli organi di gestione e formazione proporzionata.',
                    'evidence_guidance' => 'Verbali, attestazioni formazione, piano awareness e riesame direzionale.',
                ],
                [
                    'code' => 'NIS2-SVC-01',
                    'title' => 'Catalogo attivita e servizi rilevanti',
                    'domain' => 'Servizi',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'D.Lgs. 138/2024 - criteri di applicazione e informazioni del soggetto',
                    'source_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                    'review_frequency_months' => 6,
                    'description' => 'Mantenere un catalogo dei servizi e delle attivita NIS rilevanti collegato a beni, fornitori, sedi e documenti.',
                    'evidence_guidance' => 'Catalogo servizi/attivita, mapping a beni inventariati, fornitori critici, sedi, referenti e data ultimo riesame.',
                ],
                [
                    'code' => 'NIS2-RISK-01',
                    'title' => 'Metodo di autovalutazione del rischio NIS2',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 - misure di gestione dei rischi',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire criteri e metodo per valutare minacce, vulnerabilita, impatti, controlli, rischio residuo e accettazioni.',
                    'evidence_guidance' => 'Metodo rischio, criteri di impatto/probabilita, ruoli di riesame, soglie di accettazione e approvazione finale.',
                ],
                [
                    'code' => 'NIS2-RISK-02',
                    'title' => 'Matrice rischio da beni, servizi e fornitori',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 21',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Produrre una matrice rischio derivata da servizi, beni inventariati, categorie NIS e fornitori rilevanti.',
                    'evidence_guidance' => 'Report matrice rischio NIS2, export inventario, criteri usati, gap aperti e piano trattamento.',
                ],
                [
                    'code' => 'NIS2-INV-01',
                    'title' => 'Inventario beni rilevanti NIS2',
                    'parent_requirement_code' => 'NIS2-SVC-01',
                    'domain' => 'Inventario',
                    'obligation_type' => 'asset_inventory',
                    'evidence_type' => 'register',
                    'delegation_level' => 'delegable',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Collegare categorie e beni IT/OT/cloud/sicurezza/identita al perimetro NIS2.',
                    'evidence_guidance' => 'Esportazione inventario filtrata per rilevanza NIS2, ambito e impatto servizio.',
                ],
                [
                    'code' => 'NIS2-CTRL-01',
                    'title' => 'Misure minime di sicurezza e piano azioni',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Controlli',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 21 e, ove applicabile, Regolamento UE 2024/2690',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg_impl/2024/2690/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mappare misure su gestione incidenti, continuita, supply chain, vulnerabilita, igiene cyber, crittografia, accessi e MFA.',
                    'evidence_guidance' => 'Assessment controlli, evidenze tecniche, stato applicabile/non applicabile, responsabile, scadenza e piano azioni.',
                ],
                [
                    'code' => 'NIS2-SUP-01',
                    'title' => 'Qualificazione fornitori e catena di fornitura',
                    'domain' => 'Fornitori',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Valutare fornitori rilevanti, criticita, CPV, evidenze richieste e scadenze di riesame.',
                    'evidence_guidance' => 'Schede fornitore NIS2, CPV, contratti, SLA, questionari, attestazioni e piano miglioramento.',
                ],
                [
                    'code' => 'NIS2-SUP-02',
                    'title' => 'CPV, contratti e obblighi verso fornitori critici',
                    'parent_requirement_code' => 'NIS2-SUP-01',
                    'domain' => 'Fornitori',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 21 - sicurezza della catena di fornitura',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Documentare CPV, criticita, clausole, obblighi di notifica, subfornitori rilevanti e riesami periodici.',
                    'evidence_guidance' => 'Export fornitori ACN, CPV, contratti/DPA/SLA, questionari, attestazioni, notifiche e piano miglioramento.',
                ],
                [
                    'code' => 'NIS2-INC-01',
                    'title' => 'Processo di gestione e notifica incidenti',
                    'domain' => 'Incidenti',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire ruoli, escalation, registrazione, analisi e comunicazioni degli incidenti.',
                    'evidence_guidance' => 'Procedura incidenti, registro eventi, prove di escalation, report post-incidente.',
                ],
                [
                    'code' => 'NIS2-INC-02',
                    'title' => 'Registro incidenti, scadenze e comunicazioni',
                    'parent_requirement_code' => 'NIS2-INC-01',
                    'domain' => 'Incidenti',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 23',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Tracciare incidenti significativi, valutazione iniziale, notifiche, aggiornamenti, mitigazioni e report finale.',
                    'evidence_guidance' => 'Registro incidenti, timeline notifiche, decisioni, indicatori disponibili, mitigazioni e report conclusivo.',
                ],
                [
                    'code' => 'NIS2-BC-01',
                    'title' => 'Continuita operativa, backup e ripristino',
                    'domain' => 'Continuita',
                    'obligation_type' => 'business_continuity',
                    'evidence_type' => 'technical_report',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare procedure e prove per continuita, backup e ripristino dei servizi rilevanti.',
                    'evidence_guidance' => 'Piani BC/DR, prove backup restore, risultati test e azioni correttive.',
                ],
                [
                    'code' => 'NIS2-EVD-01',
                    'title' => 'Integrita, versionamento e immutabilita delle evidenze',
                    'domain' => 'Evidenze',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'attestation',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Accountability e verificabilita delle evidenze NIS',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Garantire che documenti, allegati, assegnazioni e approvazioni abbiano traccia verificabile di integrita.',
                    'evidence_guidance' => 'Registro evidenze con checksum SHA-256, catena hash eventi, versioni firmate digitalmente e log di riesame.',
                ],
            ],
        ],
        'gdpr_eu' => [
            'pack_version' => $packVersion,
            'locale' => 'it-IT',
            'framework' => [
                'name' => 'GDPR - Evidenze documentali',
                'slug' => 'gdpr-eu-evidence',
                'description' => 'Framework essenziale per collegare documenti privacy, registri ed evidenze di riesame.',
                'compliance_objective' => 'Rendere tracciabili registri, informative, DPIA, responsabilita e riesami privacy.',
                'authority_name' => 'European Union',
                'framework_code' => 'GDPR',
                'framework_type' => 'regulation',
                'compliance_domain' => 'gdpr',
                'jurisdiction' => 'EU',
                'version' => '2016/679',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                'sort_order' => 20,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'GDPR-GOV-01',
                    'title' => 'Accountability, ruoli privacy e responsabilita',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR artt. 5, 24 e 25',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere ruoli privacy, responsabilita, decisioni approvate e criteri di accountability.',
                    'evidence_guidance' => 'Matrice ruoli privacy, nomine, policy, verbali e registro decisioni.',
                ],
                [
                    'code' => 'GDPR-ROPA-01',
                    'title' => 'Registro delle attivita di trattamento',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR art. 30',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere aggiornato il registro dei trattamenti e collegarlo ai documenti firmati.',
                    'evidence_guidance' => 'Registro trattamenti, approvazioni, versioni firmate e scadenza riesame.',
                ],
                [
                    'code' => 'GDPR-DPIA-01',
                    'title' => 'Valutazioni di impatto e rischi privacy',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR art. 35',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare DPIA, rischi residui, misure e decisioni approvate.',
                    'evidence_guidance' => 'DPIA firmate, criteri di rischio, riesami e piano azioni.',
                ],
                [
                    'code' => 'GDPR-BREACH-01',
                    'title' => 'Registro data breach, decisioni e notifiche',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Data breach',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR artt. 33 e 34',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Documentare violazioni, valutazione rischio per interessati, decisione di notifica e misure correttive.',
                    'evidence_guidance' => 'Registro breach, timeline 72 ore, valutazione rischio, comunicazioni, motivi di eventuale mancata notifica.',
                ],
                [
                    'code' => 'GDPR-PROC-01',
                    'title' => 'Responsabili, fornitori e trasferimenti',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Fornitori privacy',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR artt. 28 e 44-49',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Collegare fornitori/responsabili, DPA, sub-responsabili, trasferimenti extra UE e garanzie applicabili.',
                    'evidence_guidance' => 'Contratti/DPA, elenco responsabili, sub-responsabili, SCC/TIA ove applicabili e riesami.',
                ],
                [
                    'code' => 'GDPR-RET-01',
                    'title' => 'Conservazione, cancellazione e riesame documentale',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Retention',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'medium',
                    'official_reference' => 'GDPR art. 5',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire tempi di conservazione, cancellazione, riesame e prova delle decisioni.',
                    'evidence_guidance' => 'Policy retention, scadenziario, log riesami, evidenze cancellazione e versioni firmate.',
                ],
            ],
        ],
        'nis2_en' => [
            'pack_version' => $packVersion,
            'locale' => 'en-US',
            'framework' => [
                'name' => 'NIS2 - Self-assessment matrix',
                'slug' => 'nis2-en-self-assessment',
                'description' => 'Starter matrix for managing NIS2 documents, evidence, delegations and review cycles.',
                'compliance_objective' => 'Structure NIS2 self-assessment into traceable requirements, document evidence, responsibilities and review deadlines.',
                'authority_name' => 'European Union / National authority',
                'framework_code' => 'NIS2',
                'framework_type' => 'law',
                'compliance_domain' => 'nis2',
                'jurisdiction' => 'EU',
                'version' => '2026',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                'sort_order' => 10,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'NIS2-GOV-01',
                    'title' => 'NIS perimeter, roles and responsibilities',
                    'domain' => 'Governance',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 20 and national transposition',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define the NIS perimeter, accountable roles, operational delegations, contact points and approval responsibilities.',
                    'evidence_guidance' => 'NIS perimeter register, responsibility matrix, delegations, contact points and approval minutes.',
                    'applicability_notes' => 'Governance requirement: no risk score is stored here, but primary approved evidence is required.',
                ],
                [
                    'code' => 'NIS2-REG-01',
                    'title' => 'NIS subject information update',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Registration',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 entity information and registration updates',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Keep registered NIS entity information accurate and periodically reviewed.',
                    'evidence_guidance' => 'Entity information register, responsible contacts, locations, relevant services and last review date.',
                    'applicability_notes' => 'Review when company data, perimeter, contacts or relevant services change.',
                ],
                [
                    'code' => 'NIS2-GOV-02',
                    'title' => 'Management approval, training and awareness',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Governance',
                    'obligation_type' => 'training',
                    'evidence_type' => 'training_record',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 20',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Track approval of measures, management body responsibilities and proportionate cybersecurity training.',
                    'evidence_guidance' => 'Minutes, training attestations, awareness plan and management review.',
                ],
                [
                    'code' => 'NIS2-SVC-01',
                    'title' => 'Relevant activities and services catalogue',
                    'domain' => 'Services',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 entity scope and registered information',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Maintain a catalogue of relevant NIS services and activities linked to assets, suppliers, locations and documents.',
                    'evidence_guidance' => 'Service/activity catalogue, mapping to inventoried assets, critical suppliers, locations, contacts and last review date.',
                ],
                [
                    'code' => 'NIS2-RISK-01',
                    'title' => 'NIS2 risk self-assessment method',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 cybersecurity risk-management measures',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define criteria and method to assess threats, vulnerabilities, impacts, controls, residual risk and acceptances.',
                    'evidence_guidance' => 'Risk method, impact/likelihood criteria, review roles, acceptance thresholds and final approval.',
                ],
                [
                    'code' => 'NIS2-RISK-02',
                    'title' => 'Risk matrix from assets, services and suppliers',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 21',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Produce a risk matrix derived from services, inventoried assets, NIS categories and relevant suppliers.',
                    'evidence_guidance' => 'NIS2 risk matrix report, inventory export, criteria used, open gaps and treatment plan.',
                ],
                [
                    'code' => 'NIS2-INV-01',
                    'title' => 'NIS2 relevant asset inventory',
                    'parent_requirement_code' => 'NIS2-SVC-01',
                    'domain' => 'Inventory',
                    'obligation_type' => 'asset_inventory',
                    'evidence_type' => 'register',
                    'delegation_level' => 'delegable',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Connect IT, OT, cloud, security and identity assets and categories to the NIS2 perimeter.',
                    'evidence_guidance' => 'Inventory export filtered by NIS2 relevance, inventory scope and service impact.',
                ],
                [
                    'code' => 'NIS2-CTRL-01',
                    'title' => 'Minimum security measures and action plan',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Controls',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 21 and, where applicable, Implementing Regulation (EU) 2024/2690',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg_impl/2024/2690/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Map measures for incident handling, continuity, supply chain, vulnerabilities, cyber hygiene, cryptography, access and MFA.',
                    'evidence_guidance' => 'Controls assessment, technical evidence, applicable/not applicable status, owner, deadline and action plan.',
                ],
                [
                    'code' => 'NIS2-SUP-01',
                    'title' => 'Supplier and supply-chain qualification',
                    'domain' => 'Suppliers',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Assess relevant suppliers, criticality, CPV links, required evidence and review deadlines.',
                    'evidence_guidance' => 'NIS2 supplier records, CPV codes, contracts, SLAs, questionnaires, attestations and improvement plans.',
                ],
                [
                    'code' => 'NIS2-SUP-02',
                    'title' => 'CPV, contracts and duties for critical suppliers',
                    'parent_requirement_code' => 'NIS2-SUP-01',
                    'domain' => 'Suppliers',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 21 - supply-chain security',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Document CPV codes, criticality, clauses, notification duties, relevant sub-suppliers and periodic reviews.',
                    'evidence_guidance' => 'Supplier export, CPV, contracts/DPA/SLA, questionnaires, attestations, notifications and improvement plan.',
                ],
                [
                    'code' => 'NIS2-INC-01',
                    'title' => 'Incident management and notification process',
                    'domain' => 'Incidents',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define roles, escalation, recording, analysis and incident communications.',
                    'evidence_guidance' => 'Incident procedure, event register, escalation tests and post-incident reports.',
                ],
                [
                    'code' => 'NIS2-INC-02',
                    'title' => 'Incident register, deadlines and communications',
                    'parent_requirement_code' => 'NIS2-INC-01',
                    'domain' => 'Incidents',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 23',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Track significant incidents, initial assessment, notifications, updates, mitigation and final report.',
                    'evidence_guidance' => 'Incident register, notification timeline, decisions, available indicators, mitigations and final report.',
                ],
                [
                    'code' => 'NIS2-BC-01',
                    'title' => 'Business continuity, backup and recovery',
                    'domain' => 'Continuity',
                    'obligation_type' => 'business_continuity',
                    'evidence_type' => 'technical_report',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Govern procedures and tests for continuity, backup and recovery of relevant services.',
                    'evidence_guidance' => 'BC/DR plans, backup restore tests, test results and corrective actions.',
                ],
                [
                    'code' => 'NIS2-EVD-01',
                    'title' => 'Evidence integrity, versioning and immutability',
                    'domain' => 'Evidence',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'attestation',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS evidence accountability and verifiability',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Ensure documents, attachments, assignments and approvals have a verifiable integrity trail.',
                    'evidence_guidance' => 'Evidence register with SHA-256 checksums, event hash chain, digitally signed versions and review logs.',
                ],
            ],
        ],
        'gdpr_en' => [
            'pack_version' => $packVersion,
            'locale' => 'en-US',
            'framework' => [
                'name' => 'GDPR - Document evidence',
                'slug' => 'gdpr-en-evidence',
                'description' => 'Essential framework for linking privacy documents, records and review evidence.',
                'compliance_objective' => 'Make records, notices, DPIAs, responsibilities and privacy reviews traceable.',
                'authority_name' => 'European Union',
                'framework_code' => 'GDPR',
                'framework_type' => 'regulation',
                'compliance_domain' => 'gdpr',
                'jurisdiction' => 'EU',
                'version' => '2016/679',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                'sort_order' => 20,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'GDPR-GOV-01',
                    'title' => 'Accountability, privacy roles and responsibilities',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR arts. 5, 24 and 25',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Maintain privacy roles, responsibilities, approved decisions and accountability criteria.',
                    'evidence_guidance' => 'Privacy role matrix, appointments, policies, minutes and decision register.',
                ],
                [
                    'code' => 'GDPR-ROPA-01',
                    'title' => 'Record of processing activities',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR art. 30',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Keep the record of processing activities updated and linked to signed documents.',
                    'evidence_guidance' => 'Processing register, approvals, signed versions and review deadline.',
                ],
                [
                    'code' => 'GDPR-DPIA-01',
                    'title' => 'Privacy impact and risk assessments',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR art. 35',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Govern DPIAs, residual risks, measures and approved decisions.',
                    'evidence_guidance' => 'Signed DPIAs, risk criteria, reviews and action plan.',
                ],
                [
                    'code' => 'GDPR-BREACH-01',
                    'title' => 'Data breach register, decisions and notifications',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Data breach',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR arts. 33 and 34',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Document breaches, risk assessment for data subjects, notification decision and corrective measures.',
                    'evidence_guidance' => 'Breach register, 72-hour timeline, risk assessment, communications and reasons for any non-notification.',
                ],
                [
                    'code' => 'GDPR-PROC-01',
                    'title' => 'Processors, suppliers and transfers',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Privacy suppliers',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR arts. 28 and 44-49',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Link suppliers/processors, DPAs, sub-processors, non-EU transfers and applicable safeguards.',
                    'evidence_guidance' => 'Contracts/DPA, processor list, sub-processors, SCC/TIA where applicable and reviews.',
                ],
                [
                    'code' => 'GDPR-RET-01',
                    'title' => 'Retention, erasure and document review',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Retention',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'medium',
                    'official_reference' => 'GDPR art. 5',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define retention, erasure, review and evidence of decisions.',
                    'evidence_guidance' => 'Retention policy, schedule, review logs, erasure evidence and signed versions.',
                ],
            ],
        ],
    ];

$packs['nis2_it']['source_register'] = $sourceRegisters['nis2_it'];
$packs['nis2_it']['source_register_key'] = 'nis2_it';
$packs['nis2_en']['source_register'] = $sourceRegisters['nis2_eu'];
$packs['nis2_en']['source_register_key'] = 'nis2_eu';
$packs['gdpr_eu']['source_register'] = $sourceRegisters['gdpr_eu'];
$packs['gdpr_eu']['source_register_key'] = 'gdpr_eu';
$packs['gdpr_en']['source_register'] = $sourceRegisters['gdpr_eu'];
$packs['gdpr_en']['source_register_key'] = 'gdpr_eu';

$nis2EuItRequirements = $packs['nis2_it']['requirements'];
foreach ($nis2EuItRequirements as &$requirement) {
    if (($requirement['code'] ?? null) === 'NIS2-GOV-01') {
        $requirement['official_reference'] = 'Direttiva NIS2 art. 20';
        $requirement['source_url'] = 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj';
    }

    if (($requirement['code'] ?? null) === 'NIS2-REG-01') {
        $requirement['official_reference'] = 'Direttiva NIS2 - informazioni del soggetto e registrazione nazionale ove applicabile';
        $requirement['source_url'] = 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj';
        $requirement['description'] = 'Presidiare aggiornamento e coerenza delle informazioni del soggetto NIS secondo la baseline UE e la futura guida nazionale applicabile.';
        $requirement['evidence_guidance'] = 'Registro informazioni soggetto, responsabili, sedi, servizi rilevanti, autorita competente applicabile e data ultima verifica.';
    }

    if (($requirement['code'] ?? null) === 'NIS2-SVC-01') {
        $requirement['official_reference'] = 'Direttiva NIS2 - criteri di applicazione e informazioni del soggetto';
        $requirement['source_url'] = 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj';
    }

    if (($requirement['code'] ?? null) === 'NIS2-SUP-02') {
        $requirement['evidence_guidance'] = 'Export fornitori, CPV, contratti/DPA/SLA, questionari, attestazioni, notifiche e piano miglioramento.';
    }
}
unset($requirement);

$packs['nis2_eu_it'] = [
    'pack_version' => $packVersion,
    'locale' => 'it-IT',
    'source_register' => $sourceRegisters['nis2_eu'],
    'source_register_key' => 'nis2_eu',
    'framework' => [
        'name' => 'NIS2 UE - Matrice di autovalutazione',
        'slug' => 'nis2-eu-it-self-assessment',
        'description' => 'Matrice baseline UE per tenant in lingua italiana. Il contenuto e editabile e deve essere verificato rispetto alla guida nazionale applicabile.',
        'compliance_objective' => 'Strutturare l autovalutazione NIS2 in requisiti tracciabili, evidenze documentali, responsabilita e scadenze usando la fonte UE baseline.',
        'authority_name' => 'European Union / National authority',
        'framework_code' => 'NIS2',
        'framework_type' => 'law',
        'compliance_domain' => 'nis2',
        'jurisdiction' => 'EU',
        'version' => '2026',
        'status' => 'active',
        'review_cadence_months' => 12,
        'external_reference_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
        'sort_order' => 10,
        'is_active' => true,
    ],
    'requirements' => $nis2EuItRequirements,
];

$packs['ai_act_it'] = [
    'pack_version' => $aiActPackVersion,
    'locale' => 'it-IT',
    'source_register' => $sourceRegisters['ai_act_eu'],
    'source_register_key' => 'ai_act_eu',
    'framework' => [
        'name' => 'AI Act UE - Evidenze e classificazione',
        'slug' => 'ai-act-it-evidence-classification',
        'description' => 'Framework EU baseline per inventariare sistemi AI, classificare ruoli/rischi e collegare evidenze AI Act.',
        'compliance_objective' => 'Strutturare governance AI Act, inventario, classificazioni, evidenze high-risk/GPAI e riesami senza sostituire la valutazione consulenziale.',
        'authority_name' => 'European Union / AI Office',
        'framework_code' => 'AI-ACT',
        'framework_type' => 'regulation',
        'compliance_domain' => 'ai_act',
        'jurisdiction' => 'EU',
        'version' => '2024/1689',
        'status' => 'active',
        'review_cadence_months' => 12,
        'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'sort_order' => 30,
        'is_active' => true,
    ],
    'requirements' => $aiActItRequirements,
];

$packs['ai_act_en'] = [
    'pack_version' => $aiActPackVersion,
    'locale' => 'en-US',
    'source_register' => $sourceRegisters['ai_act_eu'],
    'source_register_key' => 'ai_act_eu',
    'framework' => [
        'name' => 'AI Act EU - Evidence and classification',
        'slug' => 'ai-act-en-evidence-classification',
        'description' => 'EU baseline framework to inventory AI systems, classify roles/risks and link AI Act evidence.',
        'compliance_objective' => 'Structure AI Act governance, inventory, classifications, high-risk/GPAI evidence and review cycles without replacing expert assessment.',
        'authority_name' => 'European Union / AI Office',
        'framework_code' => 'AI-ACT',
        'framework_type' => 'regulation',
        'compliance_domain' => 'ai_act',
        'jurisdiction' => 'EU',
        'version' => '2024/1689',
        'status' => 'active',
        'review_cadence_months' => 12,
        'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
        'sort_order' => 30,
        'is_active' => true,
    ],
    'requirements' => $aiActEnRequirements,
];

$euLocalePackLabels = self::euLocalePackLabels();

foreach ($euLocalePackLabels as $locale => $languageName) {
    $localeSlug = strtolower($locale);
    $localeKey = str_replace('-', '_', $localeSlug);

    $packs["nis2_{$localeKey}"] = [
        'pack_version' => $packVersion,
        'locale' => $locale,
        'source_register' => $sourceRegisters['nis2_eu'],
        'source_register_key' => 'nis2_eu',
        'framework' => [
            'name' => "NIS2 EU - Self-assessment matrix ({$languageName})",
            'slug' => "nis2-{$localeSlug}-self-assessment",
            'description' => 'EU baseline starter matrix for tenant bootstrap. Content is tenant-editable and should be reviewed against the applicable national NIS authority guidance.',
            'compliance_objective' => 'Structure NIS2 self-assessment into traceable requirements, document evidence, responsibilities and review deadlines using the EU baseline source.',
            'authority_name' => 'European Union / National authority',
            'framework_code' => 'NIS2',
            'framework_type' => 'law',
            'compliance_domain' => 'nis2',
            'jurisdiction' => 'EU',
            'version' => '2026',
            'status' => 'active',
            'review_cadence_months' => 12,
            'external_reference_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
            'sort_order' => 10,
            'is_active' => true,
        ],
        'requirements' => $packs['nis2_en']['requirements'],
    ];

    $packs["gdpr_{$localeKey}"] = [
        'pack_version' => $packVersion,
        'locale' => $locale,
        'source_register' => $sourceRegisters['gdpr_eu'],
        'source_register_key' => 'gdpr_eu',
        'framework' => [
            'name' => "GDPR EU - Document evidence ({$languageName})",
            'slug' => "gdpr-{$localeSlug}-evidence",
            'description' => 'EU baseline framework for linking privacy documents, records and review evidence. Content is tenant-editable and should be reviewed by the responsible consultant.',
            'compliance_objective' => 'Make records, notices, DPIAs, responsibilities and privacy reviews traceable using the EU GDPR source.',
            'authority_name' => 'European Union',
            'framework_code' => 'GDPR',
            'framework_type' => 'regulation',
            'compliance_domain' => 'gdpr',
            'jurisdiction' => 'EU',
            'version' => '2016/679',
            'status' => 'active',
            'review_cadence_months' => 12,
            'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
            'sort_order' => 20,
            'is_active' => true,
        ],
        'requirements' => $packs['gdpr_en']['requirements'],
    ];

    $packs["ai_act_{$localeKey}"] = [
        'pack_version' => $aiActPackVersion,
        'locale' => $locale,
        'source_register' => $sourceRegisters['ai_act_eu'],
        'source_register_key' => 'ai_act_eu',
        'framework' => [
            'name' => "AI Act EU - Evidence and classification ({$languageName})",
            'slug' => "ai-act-{$localeSlug}-evidence-classification",
            'description' => 'EU baseline framework for tenant bootstrap. Content is tenant-editable and should be reviewed against applicable AI Office and national authority guidance.',
            'compliance_objective' => 'Structure AI Act governance, inventory, classifications, high-risk/GPAI evidence and review cycles using the EU baseline source.',
            'authority_name' => 'European Union / AI Office',
            'framework_code' => 'AI-ACT',
            'framework_type' => 'regulation',
            'compliance_domain' => 'ai_act',
            'jurisdiction' => 'EU',
            'version' => '2024/1689',
            'status' => 'active',
            'review_cadence_months' => 12,
            'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
            'sort_order' => 30,
            'is_active' => true,
        ],
        'requirements' => $packs['ai_act_en']['requirements'],
    ];
}

$nis2CountryOverlays = self::nis2CountryOverlayMatrix($sourceCheckedAt);

return [
    'source_checked_at' => $sourceCheckedAt,
    'source_registers' => $sourceRegisters,
    'nis2_country_overlays' => $nis2CountryOverlays,
    'packs' => $packs,
];
    }

    private static function nis2CountryOverlayMatrix(string $sourceCheckedAt): array
    {
        $euSources = [
            'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
            'https://digital-strategy.ec.europa.eu/en/policies/nis-transposition',
        ];

        $matrix = [
            'EU' => [
                'status' => 'baseline_only',
                'source_register_key' => 'nis2_eu',
                'jurisdiction' => 'EU',
                'pack_key' => null,
                'fallback_source_register_key' => 'nis2_eu',
                'last_checked_at' => $sourceCheckedAt,
                'sources' => $euSources,
                'notes' => 'EU baseline pack. No national transposition claim.',
            ],
            'IT' => [
                'status' => 'implemented',
                'source_register_key' => 'nis2_it',
                'jurisdiction' => 'IT/EU',
                'pack_key' => 'nis2_it',
                'fallback_source_register_key' => 'nis2_eu',
                'last_checked_at' => $sourceCheckedAt,
                'sources' => [
                    'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                    'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2024-09-04;138!vig=',
                    'https://digital-strategy.ec.europa.eu/en/policies/nis2-directive-italy',
                    'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                ],
                'notes' => 'Verified Italy national overlay. Tenant copies remain editable and are not overwritten automatically.',
            ],
        ];

        foreach ([
            'AT',
            'BE',
            'BG',
            'CY',
            'CZ',
            'DE',
            'DK',
            'EE',
            'ES',
            'FI',
            'FR',
            'GR',
            'HR',
            'HU',
            'IE',
            'LT',
            'LU',
            'LV',
            'MT',
            'NL',
            'PL',
            'PT',
            'RO',
            'SE',
            'SI',
            'SK',
        ] as $countryCode) {
            $matrix[$countryCode] = [
                'status' => 'review_required',
                'source_register_key' => null,
                'jurisdiction' => $countryCode.'/EU',
                'pack_key' => null,
                'fallback_source_register_key' => 'nis2_eu',
                'last_checked_at' => $sourceCheckedAt,
                'sources' => $euSources,
                'notes' => 'National overlay not shipped: official national source and expert review are required. Tenant bootstrap uses the EU baseline pack for now.',
            ];
        }

        ksort($matrix);

        return ['EU' => $matrix['EU']] + array_diff_key($matrix, ['EU' => true]);
    }

    private static function euLocalePackLabels(): array
    {
        return [
            'bg-BG' => 'Bulgarian',
            'ca-ES' => 'Catalan',
            'cs-CZ' => 'Czech',
            'da-DK' => 'Danish',
            'de-DE' => 'German',
            'el-GR' => 'Greek',
            'es-ES' => 'Spanish',
            'et-EE' => 'Estonian',
            'fi-FI' => 'Finnish',
            'fr-FR' => 'French',
            'ga-IE' => 'Irish',
            'hr-HR' => 'Croatian',
            'hu-HU' => 'Hungarian',
            'lt-LT' => 'Lithuanian',
            'lv-LV' => 'Latvian',
            'nl-NL' => 'Dutch',
            'pl-PL' => 'Polish',
            'pt-PT' => 'Portuguese',
            'ro-RO' => 'Romanian',
            'sk-SK' => 'Slovak',
            'sl-SI' => 'Slovenian',
            'sv-SE' => 'Swedish',
        ];
    }
}
