<?php

return [
  0 =>
  [
    'code' => 'GV.OC-04 punto 1',
    'title' => 'Elenco aggiornato dei sistemi informativi e di rete rilevanti',
    'domain' => 'Contesto organizzativo (GV.OC)',
    'obligation_type' => 'asset_inventory',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Inventario',
    'is_mandatory' => true,
    'is_active' => true,
  ],
  1 =>
  [
    'code' => 'GV.RM-03 punto 1',
    'title' => 'Piano di gestione dei rischi per la sicurezza informatica',
    'domain' => 'Strategia di gestione del rischio (GV.RM)',
    'obligation_type' => 'risk_management',
    'evidence_type' => 'procedure',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
    ],
  ],
  2 =>
  [
    'code' => 'GV.RR-02 punto 1',
    'title' => 'Organizzazione per la sicurezza informatica',
    'domain' => 'Ruoli, responsabilità e correlati poteri (GV.RR)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Nomina',
    'is_mandatory' => true,
    'is_active' => true,
  ],
  3 =>
  [
    'code' => 'GV.RR-02 punto 2',
    'title' => 'Elenco aggiornato del personale dell\'organizzazione avente specifici ruoli e responsabilità',
    'domain' => 'Ruoli, responsabilità e correlati poteri (GV.RR)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Nomina',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
    ],
  ],
  4 =>
  [
    'code' => 'GV.RR-02 punto 3',
    'title' => 'Inclusione del punto di contatto e di almeno un suo sostituto',
    'domain' => 'Ruoli, responsabilità e correlati poteri (GV.RR)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Nomina',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
    ],
  ],
  5 =>
  [
    'code' => 'GV.RR-02 punto 4',
    'title' => 'Riesamina e aggiornamento del documento ogni due anni',
    'domain' => 'Ruoli, responsabilità e correlati poteri (GV.RR)',
    'obligation_type' => 'registration',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
    ],
  ],
  6 =>
  [
    'code' => 'GV.RR-04 punto 1',
    'title' => 'Garanzia e valutazione dell’esperienza, capacità e affidabilità del personale autorizzato',
    'domain' => 'Ruoli, responsabilità e correlati poteri (GV.RR)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
  ],
  7 =>
  [
    'code' => 'GV.RR-04 punto 2',
    'title' => 'Garanzia e valutazione dell’esperienza, capacità e affidabilità degli amministratori di sistema',
    'domain' => 'Ruoli, responsabilità e correlati poteri (GV.RR)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
  ],
  8 =>
  [
    'code' => 'GV.RR-04 punto 3',
    'title' => 'Documentazione e adozione procedure di controllo sul personale',
    'domain' => 'Ruoli, responsabilità e correlati poteri (GV.RR)',
    'obligation_type' => 'registration',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-04 punto 1',
      1 => 'GV.RR-04 punto 2',
    ],
  ],
  9 =>
  [
    'code' => 'GV.PO-01 punto 1',
    'title' => 'Politiche di sicurezza informatica',
    'domain' => 'Politica (GV.PO)',
    'obligation_type' => 'governance',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 11,
    'review_frequency_months' => 1,
    'minimum_required_documents' => 11,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
  ],
  10 =>
  [
    'code' => 'GV.PO-01 punto 2',
    'title' => 'Copertura della Tabella 1 nelle politiche di sicurezza informatica',
    'domain' => 'Politica (GV.PO)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 11,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
    ],
  ],
  11 =>
  [
    'code' => 'GV.PO-01 punto 3',
    'title' => 'Approvazione delle politiche di sicurezza informatica',
    'domain' => 'Politica (GV.PO)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 11,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
    ],
  ],
  12 =>
  [
    'code' => 'GV.PO-02 punto 1',
    'title' => 'Aggiornamento annuale delle politiche di sicurezza informatica',
    'domain' => 'Politica (GV.PO)',
    'obligation_type' => 'registration',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 11,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
    ],
  ],
  13 =>
  [
    'code' => 'GV.PO-02 punto 2',
    'title' => 'Confronto tra politiche di sicurezza informatica e normativa aggiornata',
    'domain' => 'Politica (GV.PO)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 11,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Valutazione',
    'is_mandatory' => true,
    'is_active' => true,
  ],
  14 =>
  [
    'code' => 'GV.SC-01 punto 1',
    'title' => 'Processi di approvvigionamento allineati alla NIS2 e coinvolgendo l\'organizzazione per la sicurezza informatica',
    'domain' => 'Gestione del rischio di cybersecurity della catena di approvvigionamento (GV.SC)',
    'obligation_type' => 'supply_chain',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
    ],
  ],
  15 =>
  [
    'code' => 'GV.SC-02 punto 1',
    'title' => 'Comunicazione all\'ACN dei membri dell\'organizzazione per la sicurezza informatica esterni',
    'domain' => 'Gestione del rischio di cybersecurity della catena di approvvigionamento (GV.SC)',
    'obligation_type' => 'custom',
    'evidence_type' => 'other',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Nomina',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
    ],
  ],
  16 =>
  [
    'code' => 'GV.SC-02 punto 2',
    'title' => 'Personale esterno incluso nell\'organizzazione per la sicurezza informatica',
    'domain' => 'Gestione del rischio di cybersecurity della catena di approvvigionamento (GV.SC)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
    ],
  ],
  17 =>
  [
    'code' => 'GV.SC-04 punto 1',
    'title' => 'Inventario aggiornato dei fornitori',
    'domain' => 'Gestione del rischio di cybersecurity della catena di approvvigionamento (GV.SC)',
    'obligation_type' => 'supply_chain',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Inventario',
    'is_mandatory' => true,
    'is_active' => true,
  ],
  18 =>
  [
    'code' => 'GV.SC-05 punto 1',
    'title' => 'Inclusione degli standard per i fornitori dentro bandi, contratti e simili',
    'domain' => 'Gestione del rischio di cybersecurity della catena di approvvigionamento (GV.SC)',
    'obligation_type' => 'supply_chain',
    'evidence_type' => 'contract',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.SC-01 punto 1',
      1 => 'GV.RR-02 punto 1',
    ],
  ],
  19 =>
  [
    'code' => 'GV.SC-07 punto 1',
    'title' => 'Considerazione rischi posti da un fornitore ai fini ID.RA-05',
    'domain' => 'Gestione del rischio di cybersecurity della catena di approvvigionamento (GV.SC)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.SC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
    ],
  ],
  20 =>
  [
    'code' => 'GV.SC-07 punto 2',
    'title' => 'Documentazione periodica della conformità delle forniture',
    'domain' => 'Gestione del rischio di cybersecurity della catena di approvvigionamento (GV.SC)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.SC-04 punto 1',
    ],
  ],
  21 =>
  [
    'code' => 'ID.AM-01 punto 1',
    'title' => 'Inventario aggiornato di tutti gli apparati fisici autorizzati',
    'domain' => 'Gestione degli asset (ID.AM)',
    'obligation_type' => 'asset_inventory',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Inventario',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
    ],
  ],
  22 =>
  [
    'code' => 'ID.AM-02 punto 1',
    'title' => 'Inventario aggiornato di tutti i software',
    'domain' => 'Gestione degli asset (ID.AM)',
    'obligation_type' => 'asset_inventory',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Inventario',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
    ],
  ],
  23 =>
  [
    'code' => 'ID.AM-04 punto 1',
    'title' => 'Inventario aggiornato di tutti i servizi di fornitori',
    'domain' => 'Gestione degli asset (ID.AM)',
    'obligation_type' => 'supply_chain',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Inventario',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
    ],
  ],
  24 =>
  [
    'code' => 'ID.RA-01 punto 1',
    'title' => 'Utilizzo dei canali ufficiali come criterio di valutazione del rischio in ID.RA-05',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
    ],
  ],
  25 =>
  [
    'code' => 'ID.RA-05 punto 1',
    'title' => 'Valutazione del rischio posto alla sicurezza dei sistemi informativi e di rete',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'registration',
    'evidence_type' => 'procedure',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Valutazione',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
    ],
  ],
  26 =>
  [
    'code' => 'ID.RA-05 punto 2',
    'title' => 'Aggiornamento biennale della valutazione del rischio',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
    ],
  ],
  27 =>
  [
    'code' => 'ID.RA-05 punto 3',
    'title' => 'Approvazione della valutazione del rischio',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
    ],
  ],
  28 =>
  [
    'code' => 'ID.RA-06 punto 1',
    'title' => 'Piano di trattamento del rischio',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'risk_management',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 5,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
    ],
  ],
  29 =>
  [
    'code' => 'ID.RA-06 punto 2',
    'title' => 'Mitigazioni alternative incluse in ID.RA-06',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'procedure',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 5,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
    ],
  ],
  30 =>
  [
    'code' => 'ID.RA-06 punto 3',
    'title' => 'Approvazione del piano di trattamento del rischio',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 5,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'ID.RA-06 punto 1',
    ],
  ],
  31 =>
  [
    'code' => 'ID.RA-08 punto 1',
    'title' => 'Monitoraggio CSIRT Italia, CERT e ISAC',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'risk_management',
    'evidence_type' => 'procedure',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 3,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-01 punto 1',
      1 => 'ID.RA-08 punto 3',
    ],
  ],
  32 =>
  [
    'code' => 'ID.RA-08 punto 2',
    'title' => 'Risoluzione, mitigazione o accettazione di tutto il rilevato',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'technical_report',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 5,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-06 punto 1',
    ],
  ],
  33 =>
  [
    'code' => 'ID.RA-08 punto 3',
    'title' => 'Piano di gestione delle vulnerabilità',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'risk_management',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 3,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
      1 => 'GV.RR-02 punto 1',
    ],
  ],
  34 =>
  [
    'code' => 'ID.RA-08 punto 5',
    'title' => 'Monitoraggio dei canali dei fornitori di software critico',
    'domain' => 'Valutazione del rischio (Risk Assessment) (ID.RA)',
    'obligation_type' => 'risk_management',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 3,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Procedura',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-08 punto 3',
    ],
  ],
  35 =>
  [
    'code' => 'ID.IM-01 punto 1',
    'title' => 'Piano di adeguamento',
    'domain' => 'Miglioramento (ID.IM)',
    'obligation_type' => 'risk_management',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 10,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
      1 => 'GV.RR-02 punto 1',
      2 => 'ID.RA-05 punto 1',
    ],
  ],
  36 =>
  [
    'code' => 'ID.IM-01 punto 2',
    'title' => 'Relazioni periodiche agli organi amministrativi/direttivi sul piano di adeguamento',
    'domain' => 'Miglioramento (ID.IM)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 10,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Verbale',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.IM-01 punto 1',
    ],
  ],
  37 =>
  [
    'code' => 'ID.IM-04 punto 1',
    'title' => 'Piano di continuità operativa',
    'domain' => 'Miglioramento (ID.IM)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 7,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
      1 => 'GV.RR-02 punto 1',
      2 => 'ID.RA-05 punto 1',
      3 => 'ID.RA-08 punto 3',
    ],
  ],
  38 =>
  [
    'code' => 'ID.IM-04 punto 2',
    'title' => 'Piano di ripristino in caso di disastro',
    'domain' => 'Miglioramento (ID.IM)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 8,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
      1 => 'GV.RR-02 punto 1',
      2 => 'ID.RA-05 punto 1',
      3 => 'ID.RA-08 punto 3',
    ],
  ],
  39 =>
  [
    'code' => 'ID.IM-04 punto 3',
    'title' => 'Piano per la gestione delle crisi',
    'domain' => 'Miglioramento (ID.IM)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 9,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'ID.RA-08 punto 3',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  40 =>
  [
    'code' => 'ID.IM-04 punto 4',
    'title' => 'Approvazione dei tre piani ID.IM-04.1, 2 e 3',
    'domain' => 'Miglioramento (ID.IM)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 9,
    'minimum_required_documents' => 4,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.IM-04 punto 1',
      2 => 'ID.IM-04 punto 2',
      3 => 'ID.IM-04 punto 3',
    ],
  ],
  41 =>
  [
    'code' => 'ID.IM-04 punto 5',
    'title' => 'Aggiornamento biennale dei tre piani ID.IM-04.1, 2 e 3',
    'domain' => 'Miglioramento (ID.IM)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 9,
    'minimum_required_documents' => 4,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.IM-04 punto 1',
      2 => 'ID.IM-04 punto 2',
      3 => 'ID.IM-04 punto 3',
    ],
  ],
  42 =>
  [
    'code' => 'PR.AA-01 punto 1',
    'title' => 'Inventario aggiornato di tutti gli accessi normali, privilegiati e da remoto',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'asset_inventory',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Inventario',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
    ],
  ],
  43 =>
  [
    'code' => 'PR.AA-01 punto 2',
    'title' => 'Password robuste e aggiornate',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  44 =>
  [
    'code' => 'PR.AA-01 punto 3',
    'title' => 'Terminazione aggiornata degli accessi',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.AA-01 punto 1',
    ],
  ],
  45 =>
  [
    'code' => 'PR.AA-01 punto 4',
    'title' => 'Documentazione comprova PR.AA-01 punti 1, 2 e 3',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.AA-01 punto 1',
      2 => 'PR.AA-01 punto 2',
      3 => 'PR.AA-01 punto 3',
      4 => 'GV.PO-01 punto 1',
    ],
  ],
  46 =>
  [
    'code' => 'PR.AA-03 punto 1',
    'title' => 'Valutazione del rischio legato alle utenze',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Valutazione',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  47 =>
  [
    'code' => 'PR.AA-03 punto 2',
    'title' => 'MFA per almeno i sistemi di rete rilevanti',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
    ],
  ],
  48 =>
  [
    'code' => 'PR.AA-03 punto 3',
    'title' => 'Documentazione comprova PR.AA-03 punti 1 e 2',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.AA-03 punto 1',
      2 => 'PR.AA-03 punto 2',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  49 =>
  [
    'code' => 'PR.AA-05 punto 1',
    'title' => 'Least privilege sulle utenze',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'PR.AA-01 punto 1',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  50 =>
  [
    'code' => 'PR.AA-05 punto 2',
    'title' => 'Credenziali diverse per utente con diversi privilegi',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.RA-01 punto 1',
      2 => 'PR.AA-01 punto 1',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  51 =>
  [
    'code' => 'PR.AA-05 punto 3',
    'title' => 'Documentazione comprova PR.AA-05 punto 1 e 2',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.AA-05 punto 1',
      2 => 'PR.AA-05 punto 2',
    ],
  ],
  52 =>
  [
    'code' => 'PR.AA-06 punto 1',
    'title' => 'Accesso fisico protetto per almeno i sistemi rilevanti',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  53 =>
  [
    'code' => 'PR.AA-06 punto 2',
    'title' => 'Documentazione comprova PR.AA-06 punto 1',
    'domain' => 'Gestione delle identità, autenticazione e controllo degli accessi (PR.AA)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  54 =>
  [
    'code' => 'PR.AT-01 punto 1',
    'title' => 'Piano di formazione in materia di sicurezza informatica',
    'domain' => 'Consapevolezza e formazione (PR.AT)',
    'obligation_type' => 'training',
    'evidence_type' => 'training_record',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 4,
    'review_frequency_months' => 1,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  55 =>
  [
    'code' => 'PR.AT-01 punto 2',
    'title' => 'Approvazione del piano di formazione',
    'domain' => 'Consapevolezza e formazione (PR.AT)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 4,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'PR.AT-01 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  56 =>
  [
    'code' => 'PR.AT-01 punto 3',
    'title' => 'Registro aggiornato dell\'avvenuta formazione con elenco dipendenti',
    'domain' => 'Consapevolezza e formazione (PR.AT)',
    'obligation_type' => 'training',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 4,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Verbale',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'PR.AT-01 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  57 =>
  [
    'code' => 'PR.DS-01 punto 1',
    'title' => 'Cifratura su tutti i dispositivi',
    'domain' => 'Sicurezza dei dati (PR.DS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.AM-01 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  58 =>
  [
    'code' => 'PR.DS-01 punto 2',
    'title' => 'Autoplay disattivato, scansione dei supporti mobili prima dell\'apertura su PC',
    'domain' => 'Sicurezza dei dati (PR.DS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  59 =>
  [
    'code' => 'PR.DS-01 punto 3',
    'title' => 'Documentazione comprova PR.DS-01 punti 1 e 2',
    'domain' => 'Sicurezza dei dati (PR.DS)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.DS-01 punto 1',
      2 => 'PR.DS-01 punto 2',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  60 =>
  [
    'code' => 'PR.DS-02 punto 1',
    'title' => 'Protocolli e cifratura per la trasmissione di dati inclusi audio, video e testuali',
    'domain' => 'Sicurezza dei dati (PR.DS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  61 =>
  [
    'code' => 'PR.DS-02 punto 2',
    'title' => 'Documentazione comprova cifrature e protocolli di PR.DS-02 punto 1',
    'domain' => 'Sicurezza dei dati (PR.DS)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.DS-02 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  62 =>
  [
    'code' => 'PR.DS-11 punto 1',
    'title' => 'Backup periodici, anche offline',
    'domain' => 'Sicurezza dei dati (PR.DS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  63 =>
  [
    'code' => 'PR.DS-11 punto 2',
    'title' => 'Documentazione comprova PR.DS-11 punto 1',
    'domain' => 'Sicurezza dei dati (PR.DS)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.DS-11 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  64 =>
  [
    'code' => 'PR.PS-02 punto 1',
    'title' => 'Presenza esclusiva di software con aggiornamenti di sicurezza garantiti',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.AM-02 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  65 =>
  [
    'code' => 'PR.PS-02 punto 2',
    'title' => 'Aggiornamenti di sicurezza installati tempestivamente',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.RA-08 punto 5',
      2 => 'ID.RA-05 punto 1',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  66 =>
  [
    'code' => 'PR.PS-02 punto 3',
    'title' => 'Documentazione comprova PR.PS-02 punti 1 e 2',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'PR.PS-02 punto 1',
      1 => 'PR.PS-02 punto 2',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  67 =>
  [
    'code' => 'PR.PS-04 punto 1',
    'title' => 'Registrazione log di accessi da remoto e privilegiati',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  68 =>
  [
    'code' => 'PR.PS-04 punto 2',
    'title' => 'Conservazione sicura dei log per monitorare la sicurezza',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.PS-04 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  69 =>
  [
    'code' => 'PR.PS-04 punto 3',
    'title' => 'Definizione delle tempistiche di conservazione dei log',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'registration',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.PS-04 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  70 =>
  [
    'code' => 'PR.PS-04 punto 4',
    'title' => 'Documentazione comprova PR.PS-04 punti 1 e 2',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'PR.PS-04 punto 1',
      2 => 'PR.PS-04 punto 2',
    ],
  ],
  71 =>
  [
    'code' => 'PR.PS-06 punto 1',
    'title' => 'Sviluppo sicuro del codice',
    'domain' => 'Sicurezza delle piattaforme (PR.PS)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  72 =>
  [
    'code' => 'PR.IR-01 punto 1',
    'title' => 'Definizione delle attività consentite da remoto e con quali accessi',
    'domain' => 'Resilienza dell\'infrastruttura tecnologica (PR.IR)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.RA-05 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  73 =>
  [
    'code' => 'PR.IR-01 punto 2',
    'title' => 'Elenco aggiornato dei sistemi accessibili da remoto e con quali accessi',
    'domain' => 'Resilienza dell\'infrastruttura tecnologica (PR.IR)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'PR.AA-01 punto 1',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  74 =>
  [
    'code' => 'PR.IR-01 punto 3',
    'title' => 'Presenza mantenuta e aggiornata di firewall e difese perimetrali',
    'domain' => 'Resilienza dell\'infrastruttura tecnologica (PR.IR)',
    'obligation_type' => 'asset_inventory',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Inventario',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.AM-01 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  75 =>
  [
    'code' => 'PR.IR-01 punto 4',
    'title' => 'Documentazione comprova PR.IR-01 punti 1, 2 e 3',
    'domain' => 'Resilienza dell\'infrastruttura tecnologica (PR.IR)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.OC-04 punto 1',
      1 => 'PR.IR-01 punto 3',
      2 => 'ID.RA-05 punto 1',
      3 => 'PR.IR-01 punto 1',
      4 => 'PR.IR-01 punto 2',
    ],
  ],
  76 =>
  [
    'code' => 'DE.CM-01 punto 1',
    'title' => 'Presenza di strumenti per la notifica tempestiva degli incidenti (SIEM e mail)',
    'domain' => 'Monitoraggio continuo (DE.CM)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 1,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.RR-02 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'ID.RA-08 punto 3',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  77 =>
  [
    'code' => 'DE.CM-01 punto 2',
    'title' => 'Definizione di livelli di servizio attesi',
    'domain' => 'Monitoraggio continuo (DE.CM)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 7,
    'minimum_required_documents' => 4,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.IM-04 punto 1',
      1 => 'ID.IM-04 punto 2',
      2 => 'ID.IM-04 punto 3',
      3 => 'GV.PO-01 punto 1',
    ],
  ],
  78 =>
  [
    'code' => 'DE.CM-01 punto 3',
    'title' => 'Documentazione comprova DE.CM-01 punti 1 e 2',
    'domain' => 'Monitoraggio continuo (DE.CM)',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 7,
    'minimum_required_documents' => 3,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'DE.CM-01 punto 1',
      1 => 'DE.CM-01 punto 2',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  79 =>
  [
    'code' => 'DE.CM-09 punto 1',
    'title' => 'Antivirus e antimalware su tutti i dispositivi',
    'domain' => 'Monitoraggio continuo (DE.CM)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'ID.AM-01 punto 1',
      1 => 'ID.RA-05 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  80 =>
  [
    'code' => 'DE.CM-09 punto 2',
    'title' => 'Documentazione comprova DE.CM-09 punto 1',
    'domain' => 'Monitoraggio continuo (DE.CM',
    'obligation_type' => 'registration',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 2,
    'minimum_required_documents' => 1,
    'default_document_type_name' => 'Registro',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'DE.CM-09 punto 1',
      1 => 'ID.RA-01 punto 1',
      2 => 'GV.PO-01 punto 1',
    ],
  ],
  81 =>
  [
    'code' => 'RS.MA-01 punto 1',
    'title' => 'Piano per la gestione degli incidenti di sicurezza informatica',
    'domain' => 'Gestione degli incidenti (RS.MA)',
    'obligation_type' => 'risk_management',
    'evidence_type' => 'register',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 6,
    'review_frequency_months' => 2,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Piano',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'GV.PO-01 punto 1',
    ],
  ],
  82 =>
  [
    'code' => 'RS.MA-01 punto 2',
    'title' => 'Approvazione del piano per la gestione degli incidenti RS.MA-01',
    'domain' => 'Gestione degli incidenti (RS.MA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 6,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'RS.MA-01 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  83 =>
  [
    'code' => 'RS.MA-01 punto 3',
    'title' => 'Aggiornamento biennale del piano RS.MA-01',
    'domain' => 'Gestione degli incidenti (RS.MA)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 6,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'RS.MA-01 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  84 =>
  [
    'code' => 'RS.CO-02 punto 1',
    'title' => 'Definizione delle comunicazioni di incidente ai destinatari dei servizi',
    'domain' => 'Segnalazione e comunicazione della risposta agli incidenti (RS.CO)',
    'obligation_type' => 'incident_notification',
    'evidence_type' => 'procedure',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 6,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Verbale',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'RS.MA-01 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  85 =>
  [
    'code' => 'RS.CO-02 punto 2',
    'title' => 'Definizione delle comunicazioni di incidente al pubblico',
    'domain' => 'Segnalazione e comunicazione della risposta agli incidenti (RS.CO)',
    'obligation_type' => 'incident_notification',
    'evidence_type' => 'procedure',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 6,
    'minimum_required_documents' => 2,
    'default_document_type_name' => 'Verbale',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'RS.MA-01 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
  86 =>
  [
    'code' => 'RC.RP-01 punto 1',
    'title' => 'Definizione delle procedure di ripristino del normale funzionamento dei sistemi',
    'domain' => 'Esecuzione del piano di ripristino dagli incidenti (RC.RP)',
    'obligation_type' => 'governance',
    'evidence_type' => 'policy',
    'delegation_level' => 'owner_review',
    'risk_level' => 'not_applicable',
    'sort_order' => 6,
    'minimum_required_documents' => 4,
    'default_document_type_name' => 'Policy',
    'is_mandatory' => true,
    'is_active' => true,
    'parent_requirement_codes' =>
    [
      0 => 'RS.MA-01 punto 1',
      1 => 'GV.PO-01 punto 1',
    ],
  ],
];
