<?php

return [
    'packs' => [
        'nis2_it' => [
            'framework' => [
                'name' => 'NIS2 Italia - Matrice di autovalutazione',
                'slug' => 'nis2-it-self-assessment',
                'description' => 'Matrice iniziale per governare documenti, evidenze, deleghe e riesami NIS2.',
                'compliance_objective' => 'Strutturare l\'autovalutazione NIS2 in requisiti tracciabili, evidenze documentali, responsabilita e scadenze di revisione.',
                'authority_name' => 'ACN',
                'framework_code' => 'NIS2-IT',
                'framework_type' => 'law',
                'compliance_domain' => 'nis2',
                'jurisdiction' => 'IT/EU',
                'version' => '2026',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                'sort_order' => 10,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'NIS2-REG-01',
                    'title' => 'Aggiornamento informazioni soggetto NIS',
                    'domain' => 'Registrazione',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'ACN FAQ NIS - Aggiornamento delle informazioni',
                    'source_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                    'review_frequency_months' => 6,
                    'description' => 'Presidiare aggiornamento e coerenza delle informazioni registrate per il soggetto NIS.',
                    'evidence_guidance' => 'Registro informazioni soggetto, responsabili, sedi, servizi rilevanti e data ultima verifica.',
                    'applicability_notes' => 'Da rivedere quando cambiano dati societari, perimetro, referenti o servizi rilevanti.',
                ],
                [
                    'code' => 'NIS2-RISK-01',
                    'title' => 'Autovalutazione generale del rischio NIS2',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'Direttiva NIS2 - misure di gestione dei rischi',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere una matrice di autovalutazione per minacce, vulnerabilita, impatti, controlli e azioni.',
                    'evidence_guidance' => 'Matrice rischio, verbale riesame, piano trattamenti, criteri di valutazione e approvazione finale.',
                ],
                [
                    'code' => 'NIS2-INV-01',
                    'title' => 'Inventario beni rilevanti NIS2',
                    'domain' => 'Inventario',
                    'obligation_type' => 'asset_inventory',
                    'evidence_type' => 'register',
                    'delegation_level' => 'delegable',
                    'risk_level' => 'high',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Collegare categorie e beni IT/OT/cloud/sicurezza/identita al perimetro NIS2.',
                    'evidence_guidance' => 'Esportazione inventario filtrata per rilevanza NIS2, ambito e impatto servizio.',
                ],
                [
                    'code' => 'NIS2-SUP-01',
                    'title' => 'Qualificazione fornitori e catena di fornitura',
                    'domain' => 'Fornitori',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'critical',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Valutare fornitori rilevanti, criticita, CPV, evidenze richieste e scadenze di riesame.',
                    'evidence_guidance' => 'Schede fornitore NIS2, CPV, contratti, SLA, questionari, attestazioni e piano miglioramento.',
                ],
                [
                    'code' => 'NIS2-INC-01',
                    'title' => 'Processo di gestione e notifica incidenti',
                    'domain' => 'Incidenti',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire ruoli, escalation, registrazione, analisi e comunicazioni degli incidenti.',
                    'evidence_guidance' => 'Procedura incidenti, registro eventi, prove di escalation, report post-incidente.',
                ],
                [
                    'code' => 'NIS2-BC-01',
                    'title' => 'Continuita operativa, backup e ripristino',
                    'domain' => 'Continuita',
                    'obligation_type' => 'business_continuity',
                    'evidence_type' => 'technical_report',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare procedure e prove per continuita, backup e ripristino dei servizi rilevanti.',
                    'evidence_guidance' => 'Piani BC/DR, prove backup restore, risultati test e azioni correttive.',
                ],
            ],
        ],
        'gdpr_eu' => [
            'framework' => [
                'name' => 'GDPR - Evidenze documentali',
                'slug' => 'gdpr-eu-evidence',
                'description' => 'Framework essenziale per collegare documenti privacy, registri ed evidenze di riesame.',
                'compliance_objective' => 'Rendere tracciabili registri, informative, DPIA, responsabilita e riesami privacy.',
                'authority_name' => 'European Union',
                'framework_code' => 'GDPR',
                'framework_type' => 'regulation',
                'compliance_domain' => 'gdpr',
                'jurisdiction' => 'EU',
                'version' => '2016/679',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                'sort_order' => 20,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'GDPR-ROPA-01',
                    'title' => 'Registro delle attivita di trattamento',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR art. 30',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere aggiornato il registro dei trattamenti e collegarlo ai documenti firmati.',
                    'evidence_guidance' => 'Registro trattamenti, approvazioni, versioni firmate e scadenza riesame.',
                ],
                [
                    'code' => 'GDPR-DPIA-01',
                    'title' => 'Valutazioni di impatto e rischi privacy',
                    'domain' => 'Risk management',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR art. 35',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare DPIA, rischi residui, misure e decisioni approvate.',
                    'evidence_guidance' => 'DPIA firmate, criteri di rischio, riesami e piano azioni.',
                ],
            ],
        ],
    ],
];
