<?php

$packVersion = '2026.05.08.2';
$packs = [
        'nis2_it' => [
            'pack_version' => $packVersion,
            'locale' => 'it-IT',
            'framework' => [
                'name' => 'NIS2 Italia - Matrice di autovalutazione',
                'slug' => 'nis2-it-self-assessment',
                'description' => 'Matrice iniziale per governare documenti, evidenze, deleghe e riesami NIS2.',
                'compliance_objective' => 'Strutturare l\'autovalutazione NIS2 in requisiti tracciabili, evidenze documentali, responsabilita e scadenze di revisione.',
                'authority_name' => 'ACN',
                'framework_code' => 'NIS2-IT',
                'framework_type' => 'law',
                'compliance_domain' => 'nis2',
                'jurisdiction' => 'IT/EU',
                'version' => '2026',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                'sort_order' => 10,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'NIS2-GOV-01',
                    'title' => 'Perimetro, ruoli e responsabilita NIS',
                    'domain' => 'Governance',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'D.Lgs. 138/2024 e Direttiva NIS2 art. 20',
                    'source_url' => 'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2024-09-04;138!vig=',
                    'review_frequency_months' => 12,
                    'description' => 'Definire perimetro NIS, responsabili, deleghe operative, punti di contatto e responsabilita di approvazione.',
                    'evidence_guidance' => 'Registro perimetro NIS, organigramma responsabilita, deleghe, punti di contatto e verbale di approvazione.',
                    'applicability_notes' => 'Requisito di governo: non contiene punteggio di rischio, ma deve avere evidenza primaria approvata.',
                ],
                [
                    'code' => 'NIS2-REG-01',
                    'title' => 'Aggiornamento informazioni soggetto NIS',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Registrazione',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'ACN FAQ NIS - Aggiornamento delle informazioni',
                    'source_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                    'review_frequency_months' => 6,
                    'description' => 'Presidiare aggiornamento e coerenza delle informazioni registrate per il soggetto NIS.',
                    'evidence_guidance' => 'Registro informazioni soggetto, responsabili, sedi, servizi rilevanti e data ultima verifica.',
                    'applicability_notes' => 'Da rivedere quando cambiano dati societari, perimetro, referenti o servizi rilevanti.',
                ],
                [
                    'code' => 'NIS2-GOV-02',
                    'title' => 'Approvazione direzione, formazione e consapevolezza',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Governance',
                    'obligation_type' => 'training',
                    'evidence_type' => 'training_record',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 20',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Tracciare approvazione delle misure, responsabilita degli organi di gestione e formazione proporzionata.',
                    'evidence_guidance' => 'Verbali, attestazioni formazione, piano awareness e riesame direzionale.',
                ],
                [
                    'code' => 'NIS2-SVC-01',
                    'title' => 'Catalogo attivita e servizi rilevanti',
                    'domain' => 'Servizi',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'D.Lgs. 138/2024 - criteri di applicazione e informazioni del soggetto',
                    'source_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                    'review_frequency_months' => 6,
                    'description' => 'Mantenere un catalogo dei servizi e delle attivita NIS rilevanti collegato a beni, fornitori, sedi e documenti.',
                    'evidence_guidance' => 'Catalogo servizi/attivita, mapping a beni inventariati, fornitori critici, sedi, referenti e data ultimo riesame.',
                ],
                [
                    'code' => 'NIS2-RISK-01',
                    'title' => 'Metodo di autovalutazione del rischio NIS2',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 - misure di gestione dei rischi',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire criteri e metodo per valutare minacce, vulnerabilita, impatti, controlli, rischio residuo e accettazioni.',
                    'evidence_guidance' => 'Metodo rischio, criteri di impatto/probabilita, ruoli di riesame, soglie di accettazione e approvazione finale.',
                ],
                [
                    'code' => 'NIS2-RISK-02',
                    'title' => 'Matrice rischio da beni, servizi e fornitori',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 21',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Produrre una matrice rischio derivata da servizi, beni inventariati, categorie NIS e fornitori rilevanti.',
                    'evidence_guidance' => 'Report matrice rischio NIS2, export inventario, criteri usati, gap aperti e piano trattamento.',
                ],
                [
                    'code' => 'NIS2-INV-01',
                    'title' => 'Inventario beni rilevanti NIS2',
                    'parent_requirement_code' => 'NIS2-SVC-01',
                    'domain' => 'Inventario',
                    'obligation_type' => 'asset_inventory',
                    'evidence_type' => 'register',
                    'delegation_level' => 'delegable',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Collegare categorie e beni IT/OT/cloud/sicurezza/identita al perimetro NIS2.',
                    'evidence_guidance' => 'Esportazione inventario filtrata per rilevanza NIS2, ambito e impatto servizio.',
                ],
                [
                    'code' => 'NIS2-CTRL-01',
                    'title' => 'Misure minime di sicurezza e piano azioni',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Controlli',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 21 e, ove applicabile, Regolamento UE 2024/2690',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg_impl/2024/2690/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mappare misure su gestione incidenti, continuita, supply chain, vulnerabilita, igiene cyber, crittografia, accessi e MFA.',
                    'evidence_guidance' => 'Assessment controlli, evidenze tecniche, stato applicabile/non applicabile, responsabile, scadenza e piano azioni.',
                ],
                [
                    'code' => 'NIS2-SUP-01',
                    'title' => 'Qualificazione fornitori e catena di fornitura',
                    'domain' => 'Fornitori',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Valutare fornitori rilevanti, criticita, CPV, evidenze richieste e scadenze di riesame.',
                    'evidence_guidance' => 'Schede fornitore NIS2, CPV, contratti, SLA, questionari, attestazioni e piano miglioramento.',
                ],
                [
                    'code' => 'NIS2-SUP-02',
                    'title' => 'CPV, contratti e obblighi verso fornitori critici',
                    'parent_requirement_code' => 'NIS2-SUP-01',
                    'domain' => 'Fornitori',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 21 - sicurezza della catena di fornitura',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Documentare CPV, criticita, clausole, obblighi di notifica, subfornitori rilevanti e riesami periodici.',
                    'evidence_guidance' => 'Export fornitori ACN, CPV, contratti/DPA/SLA, questionari, attestazioni, notifiche e piano miglioramento.',
                ],
                [
                    'code' => 'NIS2-INC-01',
                    'title' => 'Processo di gestione e notifica incidenti',
                    'domain' => 'Incidenti',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire ruoli, escalation, registrazione, analisi e comunicazioni degli incidenti.',
                    'evidence_guidance' => 'Procedura incidenti, registro eventi, prove di escalation, report post-incidente.',
                ],
                [
                    'code' => 'NIS2-INC-02',
                    'title' => 'Registro incidenti, scadenze e comunicazioni',
                    'parent_requirement_code' => 'NIS2-INC-01',
                    'domain' => 'Incidenti',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Direttiva NIS2 art. 23',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Tracciare incidenti significativi, valutazione iniziale, notifiche, aggiornamenti, mitigazioni e report finale.',
                    'evidence_guidance' => 'Registro incidenti, timeline notifiche, decisioni, indicatori disponibili, mitigazioni e report conclusivo.',
                ],
                [
                    'code' => 'NIS2-BC-01',
                    'title' => 'Continuita operativa, backup e ripristino',
                    'domain' => 'Continuita',
                    'obligation_type' => 'business_continuity',
                    'evidence_type' => 'technical_report',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare procedure e prove per continuita, backup e ripristino dei servizi rilevanti.',
                    'evidence_guidance' => 'Piani BC/DR, prove backup restore, risultati test e azioni correttive.',
                ],
                [
                    'code' => 'NIS2-EVD-01',
                    'title' => 'Integrita, versionamento e immutabilita delle evidenze',
                    'domain' => 'Evidenze',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'attestation',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'Accountability e verificabilita delle evidenze NIS',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Garantire che documenti, allegati, assegnazioni e approvazioni abbiano traccia verificabile di integrita.',
                    'evidence_guidance' => 'Registro evidenze con checksum SHA-256, catena hash eventi, versioni firmate digitalmente e log di riesame.',
                ],
            ],
        ],
        'gdpr_eu' => [
            'pack_version' => $packVersion,
            'locale' => 'it-IT',
            'framework' => [
                'name' => 'GDPR - Evidenze documentali',
                'slug' => 'gdpr-eu-evidence',
                'description' => 'Framework essenziale per collegare documenti privacy, registri ed evidenze di riesame.',
                'compliance_objective' => 'Rendere tracciabili registri, informative, DPIA, responsabilita e riesami privacy.',
                'authority_name' => 'European Union',
                'framework_code' => 'GDPR',
                'framework_type' => 'regulation',
                'compliance_domain' => 'gdpr',
                'jurisdiction' => 'EU',
                'version' => '2016/679',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                'sort_order' => 20,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'GDPR-GOV-01',
                    'title' => 'Accountability, ruoli privacy e responsabilita',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR artt. 5, 24 e 25',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere ruoli privacy, responsabilita, decisioni approvate e criteri di accountability.',
                    'evidence_guidance' => 'Matrice ruoli privacy, nomine, policy, verbali e registro decisioni.',
                ],
                [
                    'code' => 'GDPR-ROPA-01',
                    'title' => 'Registro delle attivita di trattamento',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR art. 30',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere aggiornato il registro dei trattamenti e collegarlo ai documenti firmati.',
                    'evidence_guidance' => 'Registro trattamenti, approvazioni, versioni firmate e scadenza riesame.',
                ],
                [
                    'code' => 'GDPR-DPIA-01',
                    'title' => 'Valutazioni di impatto e rischi privacy',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR art. 35',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare DPIA, rischi residui, misure e decisioni approvate.',
                    'evidence_guidance' => 'DPIA firmate, criteri di rischio, riesami e piano azioni.',
                ],
                [
                    'code' => 'GDPR-BREACH-01',
                    'title' => 'Registro data breach, decisioni e notifiche',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Data breach',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR artt. 33 e 34',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Documentare violazioni, valutazione rischio per interessati, decisione di notifica e misure correttive.',
                    'evidence_guidance' => 'Registro breach, timeline 72 ore, valutazione rischio, comunicazioni, motivi di eventuale mancata notifica.',
                ],
                [
                    'code' => 'GDPR-PROC-01',
                    'title' => 'Responsabili, fornitori e trasferimenti',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Fornitori privacy',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR artt. 28 e 44-49',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Collegare fornitori/responsabili, DPA, sub-responsabili, trasferimenti extra UE e garanzie applicabili.',
                    'evidence_guidance' => 'Contratti/DPA, elenco responsabili, sub-responsabili, SCC/TIA ove applicabili e riesami.',
                ],
                [
                    'code' => 'GDPR-RET-01',
                    'title' => 'Conservazione, cancellazione e riesame documentale',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Retention',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'medium',
                    'official_reference' => 'GDPR art. 5',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire tempi di conservazione, cancellazione, riesame e prova delle decisioni.',
                    'evidence_guidance' => 'Policy retention, scadenziario, log riesami, evidenze cancellazione e versioni firmate.',
                ],
            ],
        ],
        'nis2_en' => [
            'pack_version' => $packVersion,
            'locale' => 'en-US',
            'framework' => [
                'name' => 'NIS2 - Self-assessment matrix',
                'slug' => 'nis2-en-self-assessment',
                'description' => 'Starter matrix for managing NIS2 documents, evidence, delegations and review cycles.',
                'compliance_objective' => 'Structure NIS2 self-assessment into traceable requirements, document evidence, responsibilities and review deadlines.',
                'authority_name' => 'European Union / National authority',
                'framework_code' => 'NIS2',
                'framework_type' => 'law',
                'compliance_domain' => 'nis2',
                'jurisdiction' => 'EU',
                'version' => '2026',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                'sort_order' => 10,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'NIS2-GOV-01',
                    'title' => 'NIS perimeter, roles and responsibilities',
                    'domain' => 'Governance',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 20 and national transposition',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define the NIS perimeter, accountable roles, operational delegations, contact points and approval responsibilities.',
                    'evidence_guidance' => 'NIS perimeter register, responsibility matrix, delegations, contact points and approval minutes.',
                    'applicability_notes' => 'Governance requirement: no risk score is stored here, but primary approved evidence is required.',
                ],
                [
                    'code' => 'NIS2-REG-01',
                    'title' => 'NIS subject information update',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Registration',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 entity information and registration updates',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Keep registered NIS entity information accurate and periodically reviewed.',
                    'evidence_guidance' => 'Entity information register, responsible contacts, locations, relevant services and last review date.',
                    'applicability_notes' => 'Review when company data, perimeter, contacts or relevant services change.',
                ],
                [
                    'code' => 'NIS2-GOV-02',
                    'title' => 'Management approval, training and awareness',
                    'parent_requirement_code' => 'NIS2-GOV-01',
                    'domain' => 'Governance',
                    'obligation_type' => 'training',
                    'evidence_type' => 'training_record',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 20',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Track approval of measures, management body responsibilities and proportionate cybersecurity training.',
                    'evidence_guidance' => 'Minutes, training attestations, awareness plan and management review.',
                ],
                [
                    'code' => 'NIS2-SVC-01',
                    'title' => 'Relevant activities and services catalogue',
                    'domain' => 'Services',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 entity scope and registered information',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Maintain a catalogue of relevant NIS services and activities linked to assets, suppliers, locations and documents.',
                    'evidence_guidance' => 'Service/activity catalogue, mapping to inventoried assets, critical suppliers, locations, contacts and last review date.',
                ],
                [
                    'code' => 'NIS2-RISK-01',
                    'title' => 'NIS2 risk self-assessment method',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 cybersecurity risk-management measures',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define criteria and method to assess threats, vulnerabilities, impacts, controls, residual risk and acceptances.',
                    'evidence_guidance' => 'Risk method, impact/likelihood criteria, review roles, acceptance thresholds and final approval.',
                ],
                [
                    'code' => 'NIS2-RISK-02',
                    'title' => 'Risk matrix from assets, services and suppliers',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 21',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Produce a risk matrix derived from services, inventoried assets, NIS categories and relevant suppliers.',
                    'evidence_guidance' => 'NIS2 risk matrix report, inventory export, criteria used, open gaps and treatment plan.',
                ],
                [
                    'code' => 'NIS2-INV-01',
                    'title' => 'NIS2 relevant asset inventory',
                    'parent_requirement_code' => 'NIS2-SVC-01',
                    'domain' => 'Inventory',
                    'obligation_type' => 'asset_inventory',
                    'evidence_type' => 'register',
                    'delegation_level' => 'delegable',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Connect IT, OT, cloud, security and identity assets and categories to the NIS2 perimeter.',
                    'evidence_guidance' => 'Inventory export filtered by NIS2 relevance, inventory scope and service impact.',
                ],
                [
                    'code' => 'NIS2-CTRL-01',
                    'title' => 'Minimum security measures and action plan',
                    'parent_requirement_code' => 'NIS2-RISK-01',
                    'domain' => 'Controls',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 21 and, where applicable, Implementing Regulation (EU) 2024/2690',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg_impl/2024/2690/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Map measures for incident handling, continuity, supply chain, vulnerabilities, cyber hygiene, cryptography, access and MFA.',
                    'evidence_guidance' => 'Controls assessment, technical evidence, applicable/not applicable status, owner, deadline and action plan.',
                ],
                [
                    'code' => 'NIS2-SUP-01',
                    'title' => 'Supplier and supply-chain qualification',
                    'domain' => 'Suppliers',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Assess relevant suppliers, criticality, CPV links, required evidence and review deadlines.',
                    'evidence_guidance' => 'NIS2 supplier records, CPV codes, contracts, SLAs, questionnaires, attestations and improvement plans.',
                ],
                [
                    'code' => 'NIS2-SUP-02',
                    'title' => 'CPV, contracts and duties for critical suppliers',
                    'parent_requirement_code' => 'NIS2-SUP-01',
                    'domain' => 'Suppliers',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 21 - supply-chain security',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Document CPV codes, criticality, clauses, notification duties, relevant sub-suppliers and periodic reviews.',
                    'evidence_guidance' => 'ACN supplier export, CPV, contracts/DPA/SLA, questionnaires, attestations, notifications and improvement plan.',
                ],
                [
                    'code' => 'NIS2-INC-01',
                    'title' => 'Incident management and notification process',
                    'domain' => 'Incidents',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define roles, escalation, recording, analysis and incident communications.',
                    'evidence_guidance' => 'Incident procedure, event register, escalation tests and post-incident reports.',
                ],
                [
                    'code' => 'NIS2-INC-02',
                    'title' => 'Incident register, deadlines and communications',
                    'parent_requirement_code' => 'NIS2-INC-01',
                    'domain' => 'Incidents',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS2 Directive art. 23',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Track significant incidents, initial assessment, notifications, updates, mitigation and final report.',
                    'evidence_guidance' => 'Incident register, notification timeline, decisions, available indicators, mitigations and final report.',
                ],
                [
                    'code' => 'NIS2-BC-01',
                    'title' => 'Business continuity, backup and recovery',
                    'domain' => 'Continuity',
                    'obligation_type' => 'business_continuity',
                    'evidence_type' => 'technical_report',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Govern procedures and tests for continuity, backup and recovery of relevant services.',
                    'evidence_guidance' => 'BC/DR plans, backup restore tests, test results and corrective actions.',
                ],
                [
                    'code' => 'NIS2-EVD-01',
                    'title' => 'Evidence integrity, versioning and immutability',
                    'domain' => 'Evidence',
                    'obligation_type' => 'governance',
                    'evidence_type' => 'attestation',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'not_applicable',
                    'official_reference' => 'NIS evidence accountability and verifiability',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Ensure documents, attachments, assignments and approvals have a verifiable integrity trail.',
                    'evidence_guidance' => 'Evidence register with SHA-256 checksums, event hash chain, digitally signed versions and review logs.',
                ],
            ],
        ],
        'gdpr_en' => [
            'pack_version' => $packVersion,
            'locale' => 'en-US',
            'framework' => [
                'name' => 'GDPR - Document evidence',
                'slug' => 'gdpr-en-evidence',
                'description' => 'Essential framework for linking privacy documents, records and review evidence.',
                'compliance_objective' => 'Make records, notices, DPIAs, responsibilities and privacy reviews traceable.',
                'authority_name' => 'European Union',
                'framework_code' => 'GDPR',
                'framework_type' => 'regulation',
                'compliance_domain' => 'gdpr',
                'jurisdiction' => 'EU',
                'version' => '2016/679',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                'sort_order' => 20,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'GDPR-GOV-01',
                    'title' => 'Accountability, privacy roles and responsibilities',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR arts. 5, 24 and 25',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Maintain privacy roles, responsibilities, approved decisions and accountability criteria.',
                    'evidence_guidance' => 'Privacy role matrix, appointments, policies, minutes and decision register.',
                ],
                [
                    'code' => 'GDPR-ROPA-01',
                    'title' => 'Record of processing activities',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR art. 30',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Keep the record of processing activities updated and linked to signed documents.',
                    'evidence_guidance' => 'Processing register, approvals, signed versions and review deadline.',
                ],
                [
                    'code' => 'GDPR-DPIA-01',
                    'title' => 'Privacy impact and risk assessments',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Risk management',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR art. 35',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Govern DPIAs, residual risks, measures and approved decisions.',
                    'evidence_guidance' => 'Signed DPIAs, risk criteria, reviews and action plan.',
                ],
                [
                    'code' => 'GDPR-BREACH-01',
                    'title' => 'Data breach register, decisions and notifications',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Data breach',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'incident_record',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR arts. 33 and 34',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Document breaches, risk assessment for data subjects, notification decision and corrective measures.',
                    'evidence_guidance' => 'Breach register, 72-hour timeline, risk assessment, communications and reasons for any non-notification.',
                ],
                [
                    'code' => 'GDPR-PROC-01',
                    'title' => 'Processors, suppliers and transfers',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Privacy suppliers',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'contract',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR arts. 28 and 44-49',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Link suppliers/processors, DPAs, sub-processors, non-EU transfers and applicable safeguards.',
                    'evidence_guidance' => 'Contracts/DPA, processor list, sub-processors, SCC/TIA where applicable and reviews.',
                ],
                [
                    'code' => 'GDPR-RET-01',
                    'title' => 'Retention, erasure and document review',
                    'parent_requirement_code' => 'GDPR-GOV-01',
                    'domain' => 'Retention',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'medium',
                    'official_reference' => 'GDPR art. 5',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define retention, erasure, review and evidence of decisions.',
                    'evidence_guidance' => 'Retention policy, schedule, review logs, erasure evidence and signed versions.',
                ],
            ],
        ],
    ];

$euLocalePackLabels = [
    'bg-BG' => 'Bulgarian',
    'ca-ES' => 'Catalan',
    'cs-CZ' => 'Czech',
    'da-DK' => 'Danish',
    'de-DE' => 'German',
    'el-GR' => 'Greek',
    'es-ES' => 'Spanish',
    'et-EE' => 'Estonian',
    'fi-FI' => 'Finnish',
    'fr-FR' => 'French',
    'ga-IE' => 'Irish',
    'hr-HR' => 'Croatian',
    'hu-HU' => 'Hungarian',
    'lt-LT' => 'Lithuanian',
    'lv-LV' => 'Latvian',
    'nl-NL' => 'Dutch',
    'pl-PL' => 'Polish',
    'pt-PT' => 'Portuguese',
    'ro-RO' => 'Romanian',
    'sk-SK' => 'Slovak',
    'sl-SI' => 'Slovenian',
    'sv-SE' => 'Swedish',
];

foreach ($euLocalePackLabels as $locale => $languageName) {
    $localeSlug = strtolower($locale);
    $localeKey = str_replace('-', '_', $localeSlug);

    $packs["nis2_{$localeKey}"] = [
        'pack_version' => $packVersion,
        'locale' => $locale,
        'framework' => [
            'name' => "NIS2 EU - Self-assessment matrix ({$languageName})",
            'slug' => "nis2-{$localeSlug}-self-assessment",
            'description' => 'EU baseline starter matrix for tenant bootstrap. Content is tenant-editable and should be reviewed against the applicable national NIS authority guidance.',
            'compliance_objective' => 'Structure NIS2 self-assessment into traceable requirements, document evidence, responsibilities and review deadlines using the EU baseline source.',
            'authority_name' => 'European Union / National authority',
            'framework_code' => 'NIS2',
            'framework_type' => 'law',
            'compliance_domain' => 'nis2',
            'jurisdiction' => 'EU',
            'version' => '2026',
            'status' => 'active',
            'review_cadence_months' => 12,
            'external_reference_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
            'sort_order' => 10,
            'is_active' => true,
        ],
        'requirements' => $packs['nis2_en']['requirements'],
    ];

    $packs["gdpr_{$localeKey}"] = [
        'pack_version' => $packVersion,
        'locale' => $locale,
        'framework' => [
            'name' => "GDPR EU - Document evidence ({$languageName})",
            'slug' => "gdpr-{$localeSlug}-evidence",
            'description' => 'EU baseline framework for linking privacy documents, records and review evidence. Content is tenant-editable and should be reviewed by the responsible consultant.',
            'compliance_objective' => 'Make records, notices, DPIAs, responsibilities and privacy reviews traceable using the EU GDPR source.',
            'authority_name' => 'European Union',
            'framework_code' => 'GDPR',
            'framework_type' => 'regulation',
            'compliance_domain' => 'gdpr',
            'jurisdiction' => 'EU',
            'version' => '2016/679',
            'status' => 'active',
            'review_cadence_months' => 12,
            'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
            'sort_order' => 20,
            'is_active' => true,
        ],
        'requirements' => $packs['gdpr_en']['requirements'],
    ];
}

return [
    'packs' => $packs,
];
