<?php

$packVersion = '2026.05.08';
$packs = [
        'nis2_it' => [
            'pack_version' => $packVersion,
            'locale' => 'it-IT',
            'framework' => [
                'name' => 'NIS2 Italia - Matrice di autovalutazione',
                'slug' => 'nis2-it-self-assessment',
                'description' => 'Matrice iniziale per governare documenti, evidenze, deleghe e riesami NIS2.',
                'compliance_objective' => 'Strutturare l\'autovalutazione NIS2 in requisiti tracciabili, evidenze documentali, responsabilita e scadenze di revisione.',
                'authority_name' => 'ACN',
                'framework_code' => 'NIS2-IT',
                'framework_type' => 'law',
                'compliance_domain' => 'nis2',
                'jurisdiction' => 'IT/EU',
                'version' => '2026',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                'sort_order' => 10,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'NIS2-REG-01',
                    'title' => 'Aggiornamento informazioni soggetto NIS',
                    'domain' => 'Registrazione',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'ACN FAQ NIS - Aggiornamento delle informazioni',
                    'source_url' => 'https://www.acn.gov.it/portale/faq/nis/aggiornamento-delle-informazioni',
                    'review_frequency_months' => 6,
                    'description' => 'Presidiare aggiornamento e coerenza delle informazioni registrate per il soggetto NIS.',
                    'evidence_guidance' => 'Registro informazioni soggetto, responsabili, sedi, servizi rilevanti e data ultima verifica.',
                    'applicability_notes' => 'Da rivedere quando cambiano dati societari, perimetro, referenti o servizi rilevanti.',
                ],
                [
                    'code' => 'NIS2-RISK-01',
                    'title' => 'Autovalutazione generale del rischio NIS2',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'Direttiva NIS2 - misure di gestione dei rischi',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere una matrice di autovalutazione per minacce, vulnerabilita, impatti, controlli e azioni.',
                    'evidence_guidance' => 'Matrice rischio, verbale riesame, piano trattamenti, criteri di valutazione e approvazione finale.',
                ],
                [
                    'code' => 'NIS2-INV-01',
                    'title' => 'Inventario beni rilevanti NIS2',
                    'domain' => 'Inventario',
                    'obligation_type' => 'asset_inventory',
                    'evidence_type' => 'register',
                    'delegation_level' => 'delegable',
                    'risk_level' => 'high',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Collegare categorie e beni IT/OT/cloud/sicurezza/identita al perimetro NIS2.',
                    'evidence_guidance' => 'Esportazione inventario filtrata per rilevanza NIS2, ambito e impatto servizio.',
                ],
                [
                    'code' => 'NIS2-SUP-01',
                    'title' => 'Qualificazione fornitori e catena di fornitura',
                    'domain' => 'Fornitori',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'critical',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Valutare fornitori rilevanti, criticita, CPV, evidenze richieste e scadenze di riesame.',
                    'evidence_guidance' => 'Schede fornitore NIS2, CPV, contratti, SLA, questionari, attestazioni e piano miglioramento.',
                ],
                [
                    'code' => 'NIS2-INC-01',
                    'title' => 'Processo di gestione e notifica incidenti',
                    'domain' => 'Incidenti',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Definire ruoli, escalation, registrazione, analisi e comunicazioni degli incidenti.',
                    'evidence_guidance' => 'Procedura incidenti, registro eventi, prove di escalation, report post-incidente.',
                ],
                [
                    'code' => 'NIS2-BC-01',
                    'title' => 'Continuita operativa, backup e ripristino',
                    'domain' => 'Continuita',
                    'obligation_type' => 'business_continuity',
                    'evidence_type' => 'technical_report',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare procedure e prove per continuita, backup e ripristino dei servizi rilevanti.',
                    'evidence_guidance' => 'Piani BC/DR, prove backup restore, risultati test e azioni correttive.',
                ],
            ],
        ],
        'gdpr_eu' => [
            'pack_version' => $packVersion,
            'locale' => 'it-IT',
            'framework' => [
                'name' => 'GDPR - Evidenze documentali',
                'slug' => 'gdpr-eu-evidence',
                'description' => 'Framework essenziale per collegare documenti privacy, registri ed evidenze di riesame.',
                'compliance_objective' => 'Rendere tracciabili registri, informative, DPIA, responsabilita e riesami privacy.',
                'authority_name' => 'European Union',
                'framework_code' => 'GDPR',
                'framework_type' => 'regulation',
                'compliance_domain' => 'gdpr',
                'jurisdiction' => 'EU',
                'version' => '2016/679',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                'sort_order' => 20,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'GDPR-ROPA-01',
                    'title' => 'Registro delle attivita di trattamento',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR art. 30',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Mantenere aggiornato il registro dei trattamenti e collegarlo ai documenti firmati.',
                    'evidence_guidance' => 'Registro trattamenti, approvazioni, versioni firmate e scadenza riesame.',
                ],
                [
                    'code' => 'GDPR-DPIA-01',
                    'title' => 'Valutazioni di impatto e rischi privacy',
                    'domain' => 'Risk management',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR art. 35',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Governare DPIA, rischi residui, misure e decisioni approvate.',
                    'evidence_guidance' => 'DPIA firmate, criteri di rischio, riesami e piano azioni.',
                ],
            ],
        ],
        'nis2_en' => [
            'pack_version' => $packVersion,
            'locale' => 'en-US',
            'framework' => [
                'name' => 'NIS2 - Self-assessment matrix',
                'slug' => 'nis2-en-self-assessment',
                'description' => 'Starter matrix for managing NIS2 documents, evidence, delegations and review cycles.',
                'compliance_objective' => 'Structure NIS2 self-assessment into traceable requirements, document evidence, responsibilities and review deadlines.',
                'authority_name' => 'European Union / National authority',
                'framework_code' => 'NIS2',
                'framework_type' => 'law',
                'compliance_domain' => 'nis2',
                'jurisdiction' => 'EU',
                'version' => '2026',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                'sort_order' => 10,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'NIS2-REG-01',
                    'title' => 'NIS subject information update',
                    'domain' => 'Registration',
                    'obligation_type' => 'registration',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'NIS2 entity information and registration updates',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Keep registered NIS entity information accurate and periodically reviewed.',
                    'evidence_guidance' => 'Entity information register, responsible contacts, locations, relevant services and last review date.',
                    'applicability_notes' => 'Review when company data, perimeter, contacts or relevant services change.',
                ],
                [
                    'code' => 'NIS2-RISK-01',
                    'title' => 'General NIS2 risk self-assessment',
                    'domain' => 'Risk management',
                    'obligation_type' => 'risk_management',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'NIS2 cybersecurity risk-management measures',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Maintain an assessment matrix for threats, vulnerabilities, impacts, controls and actions.',
                    'evidence_guidance' => 'Risk matrix, management review minutes, treatment plan, evaluation criteria and final approval.',
                ],
                [
                    'code' => 'NIS2-INV-01',
                    'title' => 'NIS2 relevant asset inventory',
                    'domain' => 'Inventory',
                    'obligation_type' => 'asset_inventory',
                    'evidence_type' => 'register',
                    'delegation_level' => 'delegable',
                    'risk_level' => 'high',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 6,
                    'description' => 'Connect IT, OT, cloud, security and identity assets and categories to the NIS2 perimeter.',
                    'evidence_guidance' => 'Inventory export filtered by NIS2 relevance, inventory scope and service impact.',
                ],
                [
                    'code' => 'NIS2-SUP-01',
                    'title' => 'Supplier and supply-chain qualification',
                    'domain' => 'Suppliers',
                    'obligation_type' => 'supply_chain',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'critical',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Assess relevant suppliers, criticality, CPV links, required evidence and review deadlines.',
                    'evidence_guidance' => 'NIS2 supplier records, CPV codes, contracts, SLAs, questionnaires, attestations and improvement plans.',
                ],
                [
                    'code' => 'NIS2-INC-01',
                    'title' => 'Incident management and notification process',
                    'domain' => 'Incidents',
                    'obligation_type' => 'incident_reporting',
                    'evidence_type' => 'procedure',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Define roles, escalation, recording, analysis and incident communications.',
                    'evidence_guidance' => 'Incident procedure, event register, escalation tests and post-incident reports.',
                ],
                [
                    'code' => 'NIS2-BC-01',
                    'title' => 'Business continuity, backup and recovery',
                    'domain' => 'Continuity',
                    'obligation_type' => 'business_continuity',
                    'evidence_type' => 'technical_report',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'source_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Govern procedures and tests for continuity, backup and recovery of relevant services.',
                    'evidence_guidance' => 'BC/DR plans, backup restore tests, test results and corrective actions.',
                ],
            ],
        ],
        'gdpr_en' => [
            'pack_version' => $packVersion,
            'locale' => 'en-US',
            'framework' => [
                'name' => 'GDPR - Document evidence',
                'slug' => 'gdpr-en-evidence',
                'description' => 'Essential framework for linking privacy documents, records and review evidence.',
                'compliance_objective' => 'Make records, notices, DPIAs, responsibilities and privacy reviews traceable.',
                'authority_name' => 'European Union',
                'framework_code' => 'GDPR',
                'framework_type' => 'regulation',
                'compliance_domain' => 'gdpr',
                'jurisdiction' => 'EU',
                'version' => '2016/679',
                'status' => 'active',
                'review_cadence_months' => 12,
                'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                'sort_order' => 20,
                'is_active' => true,
            ],
            'requirements' => [
                [
                    'code' => 'GDPR-ROPA-01',
                    'title' => 'Record of processing activities',
                    'domain' => 'Accountability',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'register',
                    'delegation_level' => 'owner_review',
                    'risk_level' => 'high',
                    'official_reference' => 'GDPR art. 30',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Keep the record of processing activities updated and linked to signed documents.',
                    'evidence_guidance' => 'Processing register, approvals, signed versions and review deadline.',
                ],
                [
                    'code' => 'GDPR-DPIA-01',
                    'title' => 'Privacy impact and risk assessments',
                    'domain' => 'Risk management',
                    'obligation_type' => 'privacy_governance',
                    'evidence_type' => 'assessment',
                    'delegation_level' => 'consultant_only',
                    'risk_level' => 'critical',
                    'official_reference' => 'GDPR art. 35',
                    'source_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
                    'review_frequency_months' => 12,
                    'description' => 'Govern DPIAs, residual risks, measures and approved decisions.',
                    'evidence_guidance' => 'Signed DPIAs, risk criteria, reviews and action plan.',
                ],
            ],
        ],
    ];

$euLocalePackLabels = [
    'bg-BG' => 'Bulgarian',
    'ca-ES' => 'Catalan',
    'cs-CZ' => 'Czech',
    'da-DK' => 'Danish',
    'de-DE' => 'German',
    'el-GR' => 'Greek',
    'es-ES' => 'Spanish',
    'et-EE' => 'Estonian',
    'fi-FI' => 'Finnish',
    'fr-FR' => 'French',
    'ga-IE' => 'Irish',
    'hr-HR' => 'Croatian',
    'hu-HU' => 'Hungarian',
    'lt-LT' => 'Lithuanian',
    'lv-LV' => 'Latvian',
    'nl-NL' => 'Dutch',
    'pl-PL' => 'Polish',
    'pt-PT' => 'Portuguese',
    'ro-RO' => 'Romanian',
    'sk-SK' => 'Slovak',
    'sl-SI' => 'Slovenian',
    'sv-SE' => 'Swedish',
];

foreach ($euLocalePackLabels as $locale => $languageName) {
    $localeSlug = strtolower($locale);
    $localeKey = str_replace('-', '_', $localeSlug);

    $packs["nis2_{$localeKey}"] = [
        'pack_version' => $packVersion,
        'locale' => $locale,
        'framework' => [
            'name' => "NIS2 EU - Self-assessment matrix ({$languageName})",
            'slug' => "nis2-{$localeSlug}-self-assessment",
            'description' => 'EU baseline starter matrix for tenant bootstrap. Content is tenant-editable and should be reviewed against the applicable national NIS authority guidance.',
            'compliance_objective' => 'Structure NIS2 self-assessment into traceable requirements, document evidence, responsibilities and review deadlines using the EU baseline source.',
            'authority_name' => 'European Union / National authority',
            'framework_code' => 'NIS2',
            'framework_type' => 'law',
            'compliance_domain' => 'nis2',
            'jurisdiction' => 'EU',
            'version' => '2026',
            'status' => 'active',
            'review_cadence_months' => 12,
            'external_reference_url' => 'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
            'sort_order' => 10,
            'is_active' => true,
        ],
        'requirements' => $packs['nis2_en']['requirements'],
    ];

    $packs["gdpr_{$localeKey}"] = [
        'pack_version' => $packVersion,
        'locale' => $locale,
        'framework' => [
            'name' => "GDPR EU - Document evidence ({$languageName})",
            'slug' => "gdpr-{$localeSlug}-evidence",
            'description' => 'EU baseline framework for linking privacy documents, records and review evidence. Content is tenant-editable and should be reviewed by the responsible consultant.',
            'compliance_objective' => 'Make records, notices, DPIAs, responsibilities and privacy reviews traceable using the EU GDPR source.',
            'authority_name' => 'European Union',
            'framework_code' => 'GDPR',
            'framework_type' => 'regulation',
            'compliance_domain' => 'gdpr',
            'jurisdiction' => 'EU',
            'version' => '2016/679',
            'status' => 'active',
            'review_cadence_months' => 12,
            'external_reference_url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
            'sort_order' => 20,
            'is_active' => true,
        ],
        'requirements' => $packs['gdpr_en']['requirements'],
    ];
}

return [
    'packs' => $packs,
];
