<?php

use App\User;

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Stripe, Mailgun, Mandrill, and others. This file provides a sane
    | default location for this type of information, allowing packages
    | to have a conventional place to find your various credentials.
    |
    */

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
    ],

    'mandrill' => [
        'secret' => env('MANDRILL_SECRET'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'stripe' => [
        'model' => User::class,
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],

    'google' => [
        'maps_api_key' => env('GOOGLE_MAPS_API'),
    ],

    /*
     * TeamSystem connectors for the ERP / management-control module.
     * Secrets live ONLY in .env (git-ignored) — never commit real tokens.
     * For production use OAuth2 per-tenant; the manual token is for setup/testing.
     */
    'fic' => [
        'base_url' => env('FIC_API_BASE_URL', 'https://api-v2.fattureincloud.it'),
        'token' => env('FIC_API_TOKEN'),
        'company_id' => env('FIC_COMPANY_ID'),
    ],

    'tspay' => [
        'base_url' => env('TSPAY_API_BASE_URL'),
        'token' => env('TSPAY_API_TOKEN'),
    ],

];
